package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * AssociatedAttribute generated by hbm2java
 */

public class AssociatedAttribute  implements java.io.Serializable {


    // Fields    

     private BigDecimal associatedAttributeId;
     private String name;
     private String description;
     private Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes = new HashSet<TaxonHasAssociatedAttribute>(0);


    // Constructors

    /** default constructor */
    public AssociatedAttribute() {
    }

	/** minimal constructor */
    public AssociatedAttribute(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }
    
    /** full constructor */
    public AssociatedAttribute(BigDecimal associatedAttributeId, String name, String description, Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes) {
        this.associatedAttributeId = associatedAttributeId;
        this.name = name;
        this.description = description;
        this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }
    

   
    // Property accessors

    public BigDecimal getAssociatedAttributeId() {
        return this.associatedAttributeId;
    }
    
    public void setAssociatedAttributeId(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set<TaxonHasAssociatedAttribute> getTaxonHasAssociatedAttributes() {
        return this.taxonHasAssociatedAttributes;
    }
    
    public void setTaxonHasAssociatedAttributes(Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes) {
        this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }
}
