/*
 *  NeoPortal - New implementation of the INBio Species and Occurrences portal.
 *  
 *  Copyright (C) 2010 INBio - Instituto Nacional de Biodiversidad, Costa Rica
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * AssociatedAttribute generated by hbm2java
 * @author asanabria
 */

public class AssociatedAttribute  
    implements java.io.Serializable {


    // Fields    

     private BigDecimal associatedAttributeId;
     private String name;
     private String description;
     private Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes 
         = new HashSet<TaxonHasAssociatedAttribute>(0);


    // Constructors

    /** default constructor */
    public AssociatedAttribute() {
    }

	/** minimal constructor */
    public AssociatedAttribute(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }
    
    /** full constructor */
    public AssociatedAttribute
        (BigDecimal associatedAttributeId,
        String name,
        String description,
        Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes) {
        
        this.associatedAttributeId = associatedAttributeId;
        this.name = name;
        this.description = description;
        this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }
    

   
    // Property accessors

    public BigDecimal getAssociatedAttributeId() {
        return this.associatedAttributeId;
    }
    
    public void setAssociatedAttributeId(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set<TaxonHasAssociatedAttribute> getTaxonHasAssociatedAttributes() {
        return this.taxonHasAssociatedAttributes;
    }
    
    public void setTaxonHasAssociatedAttributes
        (Set<TaxonHasAssociatedAttribute> taxonHasAssociatedAttributes) {
        
        this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }
}
