package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AssociatedAttribute generated by hbm2java
 */
public class AssociatedAttribute  implements java.io.Serializable {


     private BigDecimal associatedAttributeId;
     private String name;
     private String description;
     private Set taxonHasAssociatedAttributes = new HashSet(0);

    public AssociatedAttribute() {
    }

	
    public AssociatedAttribute(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }
    public AssociatedAttribute(BigDecimal associatedAttributeId, String name, String description, Set taxonHasAssociatedAttributes) {
       this.associatedAttributeId = associatedAttributeId;
       this.name = name;
       this.description = description;
       this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }
   
    public BigDecimal getAssociatedAttributeId() {
        return this.associatedAttributeId;
    }
    
    public void setAssociatedAttributeId(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTaxonHasAssociatedAttributes() {
        return this.taxonHasAssociatedAttributes;
    }
    
    public void setTaxonHasAssociatedAttributes(Set taxonHasAssociatedAttributes) {
        this.taxonHasAssociatedAttributes = taxonHasAssociatedAttributes;
    }




}


