package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;


/**
 * CommonName generated by hbm2java
 */
@Indexed
public class CommonName  implements java.io.Serializable {


    // Fields    

    @DocumentId
     private BigDecimal commonNameId;

     private Taxon taxon;

     @Field
     private String name;
     private String language;
     private String temporality;

     @Field
     private String locality;
     private String sex;
     private String lifeStage;
     private String usedBy;


    // Constructors

    /** default constructor */
    public CommonName() {
    }

	/** minimal constructor */
    public CommonName(BigDecimal commonNameId) {
        this.commonNameId = commonNameId;
    }
    
    /** full constructor */
    public CommonName(BigDecimal commonNameId, Taxon taxon, String name, String language, String temporality, String locality, String sex, String lifeStage, String usedBy) {
        this.commonNameId = commonNameId;
        this.taxon = taxon;
        this.name = name;
        this.language = language;
        this.temporality = temporality;
        this.locality = locality;
        this.sex = sex;
        this.lifeStage = lifeStage;
        this.usedBy = usedBy;
    }
    

   
    // Property accessors

    public BigDecimal getCommonNameId() {
        return this.commonNameId;
    }
    
    public void setCommonNameId(BigDecimal commonNameId) {
        this.commonNameId = commonNameId;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    public String getTemporality() {
        return this.temporality;
    }
    
    public void setTemporality(String temporality) {
        this.temporality = temporality;
    }

    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getLifeStage() {
        return this.lifeStage;
    }
    
    public void setLifeStage(String lifeStage) {
        this.lifeStage = lifeStage;
    }

    public String getUsedBy() {
        return this.usedBy;
    }
    
    public void setUsedBy(String usedBy) {
        this.usedBy = usedBy;
    }
   








}
