package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:44 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * DataProvider generated by hbm2java
 */

public class DataProvider  implements java.io.Serializable {


    // Fields    

     private BigDecimal dataProviderId;
     private String name;
     private String displayName;
     private String websiteUrl;
     private String contactEmail;
     private Set<Occurrence> occurrences = new HashSet<Occurrence>(0);
     private Set<TaxonDescription> taxonDescriptions = new HashSet<TaxonDescription>(0);


    // Constructors

    /** default constructor */
    public DataProvider() {
    }

	/** minimal constructor */
    public DataProvider(BigDecimal dataProviderId) {
        this.dataProviderId = dataProviderId;
    }
    
    /** full constructor */
    public DataProvider(BigDecimal dataProviderId, String name, String displayName, String websiteUrl, String contactEmail, Set<Occurrence> occurrences, Set<TaxonDescription> taxonDescriptions) {
        this.dataProviderId = dataProviderId;
        this.name = name;
        this.displayName = displayName;
        this.websiteUrl = websiteUrl;
        this.contactEmail = contactEmail;
        this.occurrences = occurrences;
        this.taxonDescriptions = taxonDescriptions;
    }
    

   
    // Property accessors

    public BigDecimal getDataProviderId() {
        return this.dataProviderId;
    }
    
    public void setDataProviderId(BigDecimal dataProviderId) {
        this.dataProviderId = dataProviderId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public Set<Occurrence> getOccurrences() {
        return this.occurrences;
    }
    
    public void setOccurrences(Set<Occurrence> occurrences) {
        this.occurrences = occurrences;
    }

    public Set<TaxonDescription> getTaxonDescriptions() {
        return this.taxonDescriptions;
    }
    
    public void setTaxonDescriptions(Set<TaxonDescription> taxonDescriptions) {
        this.taxonDescriptions = taxonDescriptions;
    }
   








}
