package org.inbio.neoportal.core.entity;
// Generated 09/05/2012 05:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.Indexed;
import org.inbio.neoportal.core.bridge.GeoFeatureIdBridge;

/**
 * GeoFeature generated by hbm2java
 * @author avargas
 */
@Indexed
public class GeoFeature  implements java.io.Serializable {

    @DocumentId
    @FieldBridge(
            impl=GeoFeatureIdBridge.class)
     private GeoFeatureId id;
     private GeoLayer geoLayer;
     @Field
     private String name;
     @ContainedIn
     private Set locations = new HashSet(0);

    public GeoFeature() {
    }

	
    public GeoFeature(GeoFeatureId id, GeoLayer geoLayer) {
        this.id = id;
        this.geoLayer = geoLayer;
    }
    public GeoFeature(GeoFeatureId id, GeoLayer geoLayer, String name, Set locations) {
       this.id = id;
       this.geoLayer = geoLayer;
       this.name = name;
       this.locations = locations;
    }
   
    public GeoFeatureId getId() {
        return this.id;
    }
    
    public void setId(GeoFeatureId id) {
        this.id = id;
    }
    public GeoLayer getGeoLayer() {
        return this.geoLayer;
    }
    
    public void setGeoLayer(GeoLayer geoLayer) {
        this.geoLayer = geoLayer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


