package org.inbio.neoportal.core.entity;
// Generated 09/05/2012 05:39:55 PM by Hibernate Tools 3.2.1.GA


/**
 * GeoFeatureId generated by hbm2java
 * @author avargas
 */
public class GeoFeatureId  implements java.io.Serializable {

     private long geoLayerId;
     private long geoFeatureId;

    public GeoFeatureId() {
    }

    public GeoFeatureId(long geoLayerId, long geoFeatureId) {
       this.geoLayerId = geoLayerId;
       this.geoFeatureId = geoFeatureId;
    }
   
    public long getGeoLayerId() {
        return this.geoLayerId;
    }
    
    public void setGeoLayerId(long geoLayerId) {
        this.geoLayerId = geoLayerId;
    }
    public long getGeoFeatureId() {
        return this.geoFeatureId;
    }
    
    public void setGeoFeatureId(long geoFeatureId) {
        this.geoFeatureId = geoFeatureId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GeoFeatureId) ) return false;
		 GeoFeatureId castOther = ( GeoFeatureId ) other; 
         
		 return (this.getGeoLayerId()==castOther.getGeoLayerId())
 && (this.getGeoFeatureId()==castOther.getGeoFeatureId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getGeoLayerId();
         result = 37 * result + (int) this.getGeoFeatureId();
         return result;
   }   


}


