package org.inbio.neoportal.core.entity;
// Generated 09/05/2012 05:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * GeoLayer generated by hbm2java
 */
public class GeoLayer  implements java.io.Serializable {


     private long geoLayerId;
     private String name;
     private Set geoFeatures = new HashSet(0);

    public GeoLayer() {
    }

	
    public GeoLayer(long geoLayerId) {
        this.geoLayerId = geoLayerId;
    }
    public GeoLayer(long geoLayerId, String name, Set geoFeatures) {
       this.geoLayerId = geoLayerId;
       this.name = name;
       this.geoFeatures = geoFeatures;
    }
   
    public long getGeoLayerId() {
        return this.geoLayerId;
    }
    
    public void setGeoLayerId(long geoLayerId) {
        this.geoLayerId = geoLayerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getGeoFeatures() {
        return this.geoFeatures;
    }
    
    public void setGeoFeatures(Set geoFeatures) {
        this.geoFeatures = geoFeatures;
    }




}


