package org.inbio.neoportal.core.entity;
// Generated 29/06/2012 11:52:11 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupNav generated by hbm2java
 */
public class GroupNav implements java.io.Serializable {

     private BigDecimal groupNavId;
     private String name;
     private String nameEng;
     private GroupNav groupNavParent;
     private BigDecimal taxonId;
     private Set<GroupNav> groupNavChilds = new HashSet<GroupNav>();

    public GroupNav() {
    }

	
    public GroupNav(BigDecimal groupNavId) {
        this.groupNavId = groupNavId;
    }

	public GroupNav(BigDecimal groupNavId, GroupNav groupNavParent,
			BigDecimal taxonId, Set groupNavChilds) {
		super();
		this.groupNavId = groupNavId;
		this.groupNavParent = groupNavParent;
		this.taxonId = taxonId;
		this.groupNavChilds = groupNavChilds;
	}

	public BigDecimal getGroupNavId() {
		return groupNavId;
	}

	public void setGroupNavId(BigDecimal groupNavId) {
		this.groupNavId = groupNavId;
	}

	public GroupNav getGroupNavParent() {
		return groupNavParent;
	}

	public void setGroupNavParent(GroupNav groupNavParent) {
		this.groupNavParent = groupNavParent;
	}

	public BigDecimal getTaxonId() {
		return taxonId;
	}

	public void setTaxonId(BigDecimal taxonId) {
		this.taxonId = taxonId;
	}

	public Set<GroupNav> getGroupNavChilds() {
		return groupNavChilds;
	}

	public void setGroupNavChilds(Set groupNavChilds) {
		this.groupNavChilds = groupNavChilds;
	}

	/**
	 * @return the label
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param label the label to set
	 */
	public void setName(String label) {
		this.name = label;
	}

	/**
	 * @return the nameEng
	 */
	public String getNameEng() {
		return nameEng;
	}

	/**
	 * @param nameEng the nameEng to set
	 */
	public void setNameEng(String nameEng) {
		this.nameEng = nameEng;
	}
	
}


