package org.inbio.neoportal.core.entity;
// Generated 29/06/2012 11:52:11 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupNav generated by hbm2java
 */
public class GroupNav  implements java.io.Serializable {


     private BigDecimal groupNavId;
     private GroupNav groupNavParent;
     private BigDecimal taxonId;
     private Set groupNavChilds = new HashSet(0);

    public GroupNav() {
    }

	
    public GroupNav(BigDecimal groupNavId) {
        this.groupNavId = groupNavId;
    }
    public GroupNav(BigDecimal groupNavId, GroupNav groupNav, BigDecimal taxonId, Set groupNavs) {
       this.groupNavId = groupNavId;
       this.groupNavParent = groupNav;
       this.taxonId = taxonId;
       this.groupNavChilds = groupNavs;
    }
   
    public BigDecimal getGroupNavId() {
        return this.groupNavId;
    }
    
    public void setGroupNavId(BigDecimal groupNavId) {
        this.groupNavId = groupNavId;
    }
    public GroupNav getGroupNav() {
        return this.groupNavParent;
    }
    
    public void setGroupNav(GroupNav groupNav) {
        this.groupNavParent = groupNav;
    }
    public BigDecimal getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(BigDecimal taxonId) {
        this.taxonId = taxonId;
    }
    public Set getGroupNavs() {
        return this.groupNavChilds;
    }
    
    public void setGroupNavs(Set groupNavs) {
        this.groupNavChilds = groupNavs;
    }




}


