package org.inbio.neoportal.core.entity;
// Generated 10/05/2012 09:55:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;

/**
 * Location generated by hbm2java
 * @author avargas
 */
@Indexed
public class Location  implements java.io.Serializable {

    @DocumentId
    private BigDecimal locationId;
    private String higherGeographyId;
    private String higherGeography;
    private String continent;
    private String waterBody;
    private String islandGroup;
    private String island;
    private String country;
    private String countryCode;
    private String stateProvince;
    private String county;
    private String municipality;
    private String locality;
    private String verbatimLocality;
    private String verbatimElevation;
    private String minimumElevationInMeters;
    private String maximumElevationInMeters;
    private String verbatimDepth;
    private String minimumDepthInMeters;
    private String maximumDepthInMeters;
    private String minimumDistanceAboveSurfaceInMeters;
    private String maximumDistanceAboveSurfaceInMeters;
    private String locationAccordingTo;
    private String locationRemarks;
    private String verbatimCoordinates;
    private String verbatimLatitude;
    private String verbatimLongitude;
    private String verbatimCoordinateSystem;
    private String verbatimSRS;
    private String decimalLatitude;
    private String decimalLongitude;
    private String geodeticDatum;
    private String coordinateUncertaintyInMeters;
    private String coordinatePrecision;
    private String pointRadiusSpatialFit;
    private String footprintWKT;
    private String footprintSRS;
    private String footprintSpatialFit;
    private String georeferencedBy;
    private String georeferencedDate;
    private String georeferenceProtocol;
    private String georeferenceSources;
    private String georeferenceVerificationStatus;
    private String georeferenceRemarks;
    
     @ContainedIn
     private Set occurrences = new HashSet(0);
     //feature point to location so depth should be 1
     @IndexedEmbedded(depth=1) 
     private Set features = new HashSet(0);

    public Location() {
    }

    public Location(BigDecimal locationId, String higherGeographyId,
			String higherGeography, String continent, String waterBody,
			String islandGroup, String island, String country,
			String countryCode, String stateProvince, String county,
			String municipality, String locality, String verbatimLocality,
			String verbatimElevation, String minimumElevationInMeters,
			String maximumElevationInMeters, String verbatimDepth,
			String minimumDepthInMeters, String maximumDepthInMeters,
			String minimumDistanceAboveSurfaceInMeters,
			String maximumDistanceAboveSurfaceInMeters,
			String locationAccordingTo, String locationRemarks,
			String verbatimCoordinates, String verbatimLatitude,
			String verbatimLongitude, String verbatimCoordinateSystem,
			String verbatimSRS, String decimalLatitude,
			String decimalLongitude, String geodeticDatum,
			String coordinateUncertaintyInMeters, String coordinatePrecision,
			String pointRadiusSpatialFit, String footprintWKT,
			String footprintSRS, String footprintSpatialFit,
			String georeferencedBy, String georeferencedDate,
			String georeferenceProtocol, String georeferenceSources,
			String georeferenceVerificationStatus, String georeferenceRemarks,
			Set occurrences, Set features) {
		this.locationId = locationId;
		this.higherGeographyId = higherGeographyId;
		this.higherGeography = higherGeography;
		this.continent = continent;
		this.waterBody = waterBody;
		this.islandGroup = islandGroup;
		this.island = island;
		this.country = country;
		this.countryCode = countryCode;
		this.stateProvince = stateProvince;
		this.county = county;
		this.municipality = municipality;
		this.locality = locality;
		this.verbatimLocality = verbatimLocality;
		this.verbatimElevation = verbatimElevation;
		this.minimumElevationInMeters = minimumElevationInMeters;
		this.maximumElevationInMeters = maximumElevationInMeters;
		this.verbatimDepth = verbatimDepth;
		this.minimumDepthInMeters = minimumDepthInMeters;
		this.maximumDepthInMeters = maximumDepthInMeters;
		this.minimumDistanceAboveSurfaceInMeters = minimumDistanceAboveSurfaceInMeters;
		this.maximumDistanceAboveSurfaceInMeters = maximumDistanceAboveSurfaceInMeters;
		this.locationAccordingTo = locationAccordingTo;
		this.locationRemarks = locationRemarks;
		this.verbatimCoordinates = verbatimCoordinates;
		this.verbatimLatitude = verbatimLatitude;
		this.verbatimLongitude = verbatimLongitude;
		this.verbatimCoordinateSystem = verbatimCoordinateSystem;
		this.verbatimSRS = verbatimSRS;
		this.decimalLatitude = decimalLatitude;
		this.decimalLongitude = decimalLongitude;
		this.geodeticDatum = geodeticDatum;
		this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
		this.coordinatePrecision = coordinatePrecision;
		this.pointRadiusSpatialFit = pointRadiusSpatialFit;
		this.footprintWKT = footprintWKT;
		this.footprintSRS = footprintSRS;
		this.footprintSpatialFit = footprintSpatialFit;
		this.georeferencedBy = georeferencedBy;
		this.georeferencedDate = georeferencedDate;
		this.georeferenceProtocol = georeferenceProtocol;
		this.georeferenceSources = georeferenceSources;
		this.georeferenceVerificationStatus = georeferenceVerificationStatus;
		this.georeferenceRemarks = georeferenceRemarks;
		this.occurrences = occurrences;
		this.features = features;
	}



	public Location(BigDecimal locationId) {
        this.locationId = locationId;
    }
    
   
    public BigDecimal getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(BigDecimal locationId) {
        this.locationId = locationId;
    }
    
    
    public String getHigherGeographyId() {
		return higherGeographyId;
	}


	public void setHigherGeographyId(String higherGeographyId) {
		this.higherGeographyId = higherGeographyId;
	}


	public String getHigherGeography() {
		return higherGeography;
	}


	public void setHigherGeography(String higherGeography) {
		this.higherGeography = higherGeography;
	}


	public String getContinent() {
		return continent;
	}


	public void setContinent(String continent) {
		this.continent = continent;
	}


	public String getWaterBody() {
		return waterBody;
	}


	public void setWaterBody(String waterBody) {
		this.waterBody = waterBody;
	}


	public String getIslandGroup() {
		return islandGroup;
	}


	public void setIslandGroup(String islandGroup) {
		this.islandGroup = islandGroup;
	}


	public String getIsland() {
		return island;
	}


	public void setIsland(String island) {
		this.island = island;
	}


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	public String getCountryCode() {
		return countryCode;
	}


	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}


	public String getStateProvince() {
		return stateProvince;
	}


	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}


	public String getCounty() {
		return county;
	}


	public void setCounty(String county) {
		this.county = county;
	}


	public String getMunicipality() {
		return municipality;
	}


	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}


	public String getLocality() {
		return locality;
	}


	public void setLocality(String locality) {
		this.locality = locality;
	}


	public String getVerbatimLocality() {
		return verbatimLocality;
	}


	public void setVerbatimLocality(String verbatimLocality) {
		this.verbatimLocality = verbatimLocality;
	}


	public String getVerbatimElevation() {
		return verbatimElevation;
	}


	public void setVerbatimElevation(String verbatimElevation) {
		this.verbatimElevation = verbatimElevation;
	}


	public String getMinimumElevationInMeters() {
		return minimumElevationInMeters;
	}


	public void setMinimumElevationInMeters(String minimumElevationInMeters) {
		this.minimumElevationInMeters = minimumElevationInMeters;
	}


	public String getMaximumElevationInMeters() {
		return maximumElevationInMeters;
	}


	public void setMaximumElevationInMeters(String maximumElevationInMeters) {
		this.maximumElevationInMeters = maximumElevationInMeters;
	}


	public String getVerbatimDepth() {
		return verbatimDepth;
	}


	public void setVerbatimDepth(String verbatimDepth) {
		this.verbatimDepth = verbatimDepth;
	}


	public String getMinimumDepthInMeters() {
		return minimumDepthInMeters;
	}


	public void setMinimumDepthInMeters(String minimumDepthInMeters) {
		this.minimumDepthInMeters = minimumDepthInMeters;
	}


	public String getMaximumDepthInMeters() {
		return maximumDepthInMeters;
	}


	public void setMaximumDepthInMeters(String maximumDepthInMeters) {
		this.maximumDepthInMeters = maximumDepthInMeters;
	}


	public String getMinimumDistanceAboveSurfaceInMeters() {
		return minimumDistanceAboveSurfaceInMeters;
	}


	public void setMinimumDistanceAboveSurfaceInMeters(
			String minimumDistanceAboveSurfaceInMeters) {
		this.minimumDistanceAboveSurfaceInMeters = minimumDistanceAboveSurfaceInMeters;
	}


	public String getMaximumDistanceAboveSurfaceInMeters() {
		return maximumDistanceAboveSurfaceInMeters;
	}


	public void setMaximumDistanceAboveSurfaceInMeters(
			String maximumDistanceAboveSurfaceInMeters) {
		this.maximumDistanceAboveSurfaceInMeters = maximumDistanceAboveSurfaceInMeters;
	}


	public String getLocationAccordingTo() {
		return locationAccordingTo;
	}


	public void setLocationAccordingTo(String locationAccordingTo) {
		this.locationAccordingTo = locationAccordingTo;
	}


	public String getLocationRemarks() {
		return locationRemarks;
	}


	public void setLocationRemarks(String locationRemarks) {
		this.locationRemarks = locationRemarks;
	}


	public String getVerbatimCoordinates() {
		return verbatimCoordinates;
	}


	public void setVerbatimCoordinates(String verbatimCoordinates) {
		this.verbatimCoordinates = verbatimCoordinates;
	}


	public String getVerbatimLatitude() {
		return verbatimLatitude;
	}


	public void setVerbatimLatitude(String verbatimLatitude) {
		this.verbatimLatitude = verbatimLatitude;
	}


	public String getVerbatimLongitude() {
		return verbatimLongitude;
	}


	public void setVerbatimLongitude(String verbatimLongitude) {
		this.verbatimLongitude = verbatimLongitude;
	}


	public String getVerbatimCoordinateSystem() {
		return verbatimCoordinateSystem;
	}


	public void setVerbatimCoordinateSystem(String verbatimCoordinateSystem) {
		this.verbatimCoordinateSystem = verbatimCoordinateSystem;
	}


	public String getVerbatimSRS() {
		return verbatimSRS;
	}


	public void setVerbatimSRS(String verbatimSRS) {
		this.verbatimSRS = verbatimSRS;
	}


	public String getDecimalLatitude() {
		return decimalLatitude;
	}


	public void setDecimalLatitude(String decimalLatitude) {
		this.decimalLatitude = decimalLatitude;
	}


	public String getDecimalLongitude() {
		return decimalLongitude;
	}


	public void setDecimalLongitude(String decimalLongitude) {
		this.decimalLongitude = decimalLongitude;
	}


	public String getGeodeticDatum() {
		return geodeticDatum;
	}


	public void setGeodeticDatum(String geodeticDatum) {
		this.geodeticDatum = geodeticDatum;
	}


	public String getCoordinateUncertaintyInMeters() {
		return coordinateUncertaintyInMeters;
	}


	public void setCoordinateUncertaintyInMeters(
			String coordinateUncertaintyInMeters) {
		this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
	}


	public String getCoordinatePrecision() {
		return coordinatePrecision;
	}


	public void setCoordinatePrecision(String coordinatePrecision) {
		this.coordinatePrecision = coordinatePrecision;
	}


	public String getPointRadiusSpatialFit() {
		return pointRadiusSpatialFit;
	}


	public void setPointRadiusSpatialFit(String pointRadiusSpatialFit) {
		this.pointRadiusSpatialFit = pointRadiusSpatialFit;
	}


	public String getFootprintWKT() {
		return footprintWKT;
	}


	public void setFootprintWKT(String footprintWKT) {
		this.footprintWKT = footprintWKT;
	}


	public String getFootprintSRS() {
		return footprintSRS;
	}


	public void setFootprintSRS(String footprintSRS) {
		this.footprintSRS = footprintSRS;
	}


	public String getFootprintSpatialFit() {
		return footprintSpatialFit;
	}


	public void setFootprintSpatialFit(String footprintSpatialFit) {
		this.footprintSpatialFit = footprintSpatialFit;
	}


	public String getGeoreferencedBy() {
		return georeferencedBy;
	}


	public void setGeoreferencedBy(String georeferencedBy) {
		this.georeferencedBy = georeferencedBy;
	}


	public String getGeoreferencedDate() {
		return georeferencedDate;
	}


	public void setGeoreferencedDate(String georeferencedDate) {
		this.georeferencedDate = georeferencedDate;
	}


	public String getGeoreferenceProtocol() {
		return georeferenceProtocol;
	}


	public void setGeoreferenceProtocol(String georeferenceProtocol) {
		this.georeferenceProtocol = georeferenceProtocol;
	}


	public String getGeoreferenceSources() {
		return georeferenceSources;
	}


	public void setGeoreferenceSources(String georeferenceSources) {
		this.georeferenceSources = georeferenceSources;
	}


	public String getGeoreferenceVerificationStatus() {
		return georeferenceVerificationStatus;
	}


	public void setGeoreferenceVerificationStatus(
			String georeferenceVerificationStatus) {
		this.georeferenceVerificationStatus = georeferenceVerificationStatus;
	}


	public String getGeoreferenceRemarks() {
		return georeferenceRemarks;
	}


	public void setGeoreferenceRemarks(String georeferenceRemarks) {
		this.georeferenceRemarks = georeferenceRemarks;
	}


	public Set getOccurrences() {
        return this.occurrences;
    }
    
    public void setOccurrences(Set occurrences) {
        this.occurrences = occurrences;
    }

    public Set getFeatures() {
        return features;
    }

    public void setFeatures(Set features) {
        this.features = features;
    }

}


