package org.inbio.neoportal.core.entity;
// Generated 10/05/2012 09:55:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;

/**
 * Location generated by hbm2java
 * @author avargas
 */
@Indexed
public class Location  implements java.io.Serializable {

    @DocumentId
     private BigDecimal locationId;
     @Field
     private String decimalLatitude;
     @Field
     private String decimalLongitude;
     private String geodeticDatum;
     private String coordinateUncertaintyInMeters;
     private String pointRadiusSpatialFit;
     private String footprintWkt;
     private String footPrintSpatialFit;
     private String verbatimCoordinates;
     private String verbatimLatitude;
     private String verbatimLongitude;
     private String verbatimCoordinateSystem;
     private String georeferenceProtocol;
     private String georeferenceSources;
     private String georeferenceVerificationStatus;
     private String georeferenceRemarks;
     @ContainedIn
     private Set occurrences = new HashSet(0);
     //feature point to location so depth should be 1
     @IndexedEmbedded(depth=1) 
     private Set features = new HashSet(0);

    public Location() {
    }

	
    public Location(BigDecimal locationId) {
        this.locationId = locationId;
    }
    public Location(BigDecimal locationId, String decimalLatitude, String decimalLongitude, String geodeticDatum, String coordinateUncertaintyInMeters, String pointRadiusSpatialFit, String footprintWkt, String footPrintSpatialFit, String verbatimCoordinates, String verbatimLatitude, String verbatimLongitude, String verbatimCoordinateSystem, String georeferenceProtocol, String georeferenceSources, String georeferenceVerificationStatus, String georeferenceRemarks, Set occurrences, Set features) {
       this.locationId = locationId;
       this.decimalLatitude = decimalLatitude;
       this.decimalLongitude = decimalLongitude;
       this.geodeticDatum = geodeticDatum;
       this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
       this.pointRadiusSpatialFit = pointRadiusSpatialFit;
       this.footprintWkt = footprintWkt;
       this.footPrintSpatialFit = footPrintSpatialFit;
       this.verbatimCoordinates = verbatimCoordinates;
       this.verbatimLatitude = verbatimLatitude;
       this.verbatimLongitude = verbatimLongitude;
       this.verbatimCoordinateSystem = verbatimCoordinateSystem;
       this.georeferenceProtocol = georeferenceProtocol;
       this.georeferenceSources = georeferenceSources;
       this.georeferenceVerificationStatus = georeferenceVerificationStatus;
       this.georeferenceRemarks = georeferenceRemarks;
       this.occurrences = occurrences;
       this.features = features;
    }
   
    public BigDecimal getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(BigDecimal locationId) {
        this.locationId = locationId;
    }
    public String getDecimalLatitude() {
        return this.decimalLatitude;
    }
    
    public void setDecimalLatitude(String decimalLatitude) {
        this.decimalLatitude = decimalLatitude;
    }
    public String getDecimalLongitude() {
        return this.decimalLongitude;
    }
    
    public void setDecimalLongitude(String decimalLongitude) {
        this.decimalLongitude = decimalLongitude;
    }
    public String getGeodeticDatum() {
        return this.geodeticDatum;
    }
    
    public void setGeodeticDatum(String geodeticDatum) {
        this.geodeticDatum = geodeticDatum;
    }
    public String getCoordinateUncertaintyInMeters() {
        return this.coordinateUncertaintyInMeters;
    }
    
    public void setCoordinateUncertaintyInMeters(String coordinateUncertaintyInMeters) {
        this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
    }
    public String getPointRadiusSpatialFit() {
        return this.pointRadiusSpatialFit;
    }
    
    public void setPointRadiusSpatialFit(String pointRadiusSpatialFit) {
        this.pointRadiusSpatialFit = pointRadiusSpatialFit;
    }
    public String getFootprintWkt() {
        return this.footprintWkt;
    }
    
    public void setFootprintWkt(String footprintWkt) {
        this.footprintWkt = footprintWkt;
    }
    public String getFootPrintSpatialFit() {
        return this.footPrintSpatialFit;
    }
    
    public void setFootPrintSpatialFit(String footPrintSpatialFit) {
        this.footPrintSpatialFit = footPrintSpatialFit;
    }
    public String getVerbatimCoordinates() {
        return this.verbatimCoordinates;
    }
    
    public void setVerbatimCoordinates(String verbatimCoordinates) {
        this.verbatimCoordinates = verbatimCoordinates;
    }
    public String getVerbatimLatitude() {
        return this.verbatimLatitude;
    }
    
    public void setVerbatimLatitude(String verbatimLatitude) {
        this.verbatimLatitude = verbatimLatitude;
    }
    public String getVerbatimLongitude() {
        return this.verbatimLongitude;
    }
    
    public void setVerbatimLongitude(String verbatimLongitude) {
        this.verbatimLongitude = verbatimLongitude;
    }
    public String getVerbatimCoordinateSystem() {
        return this.verbatimCoordinateSystem;
    }
    
    public void setVerbatimCoordinateSystem(String verbatimCoordinateSystem) {
        this.verbatimCoordinateSystem = verbatimCoordinateSystem;
    }
    public String getGeoreferenceProtocol() {
        return this.georeferenceProtocol;
    }
    
    public void setGeoreferenceProtocol(String georeferenceProtocol) {
        this.georeferenceProtocol = georeferenceProtocol;
    }
    public String getGeoreferenceSources() {
        return this.georeferenceSources;
    }
    
    public void setGeoreferenceSources(String georeferenceSources) {
        this.georeferenceSources = georeferenceSources;
    }
    public String getGeoreferenceVerificationStatus() {
        return this.georeferenceVerificationStatus;
    }
    
    public void setGeoreferenceVerificationStatus(String georeferenceVerificationStatus) {
        this.georeferenceVerificationStatus = georeferenceVerificationStatus;
    }
    public String getGeoreferenceRemarks() {
        return this.georeferenceRemarks;
    }
    
    public void setGeoreferenceRemarks(String georeferenceRemarks) {
        this.georeferenceRemarks = georeferenceRemarks;
    }
    public Set getOccurrences() {
        return this.occurrences;
    }
    
    public void setOccurrences(Set occurrences) {
        this.occurrences = occurrences;
    }

    public Set getFeatures() {
        return features;
    }

    public void setFeatures(Set features) {
        this.features = features;
    }

}


