package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * OccurrenceCuratorialExtension generated by hbm2java
 */
public class OccurrenceCuratorialExtension  implements java.io.Serializable {


     private BigDecimal occurrenceCuratorialExtensionId;
     private Occurrence occurrence;
     private String catalogNumberNumeric;
     private String identifiedBy;
     private String dateIdentified;
     private String collectorNumber;
     private String fieldNumber;
     private String fieldNotes;
     private String verbatimCollectingDate;
     private String verbatimElevation;
     private String verbatimDepth;
     private String preparations;
     private String typeStatus;
     private String genBankNumber;
     private String otherCatalogNumbers;
     private String relatedCatalogItems;
     private String disposition;
     private String individualCount;

    public OccurrenceCuratorialExtension() {
    }

	
    public OccurrenceCuratorialExtension(BigDecimal occurrenceCuratorialExtensionId, Occurrence occurrence) {
        this.occurrenceCuratorialExtensionId = occurrenceCuratorialExtensionId;
        this.occurrence = occurrence;
    }
    public OccurrenceCuratorialExtension(BigDecimal occurrenceCuratorialExtensionId, Occurrence occurrence, String catalogNumberNumeric, String identifiedBy, String dateIdentified, String collectorNumber, String fieldNumber, String fieldNotes, String verbatimCollectingDate, String verbatimElevation, String verbatimDepth, String preparations, String typeStatus, String genBankNumber, String otherCatalogNumbers, String relatedCatalogItems, String disposition, String individualCount) {
       this.occurrenceCuratorialExtensionId = occurrenceCuratorialExtensionId;
       this.occurrence = occurrence;
       this.catalogNumberNumeric = catalogNumberNumeric;
       this.identifiedBy = identifiedBy;
       this.dateIdentified = dateIdentified;
       this.collectorNumber = collectorNumber;
       this.fieldNumber = fieldNumber;
       this.fieldNotes = fieldNotes;
       this.verbatimCollectingDate = verbatimCollectingDate;
       this.verbatimElevation = verbatimElevation;
       this.verbatimDepth = verbatimDepth;
       this.preparations = preparations;
       this.typeStatus = typeStatus;
       this.genBankNumber = genBankNumber;
       this.otherCatalogNumbers = otherCatalogNumbers;
       this.relatedCatalogItems = relatedCatalogItems;
       this.disposition = disposition;
       this.individualCount = individualCount;
    }
   
    public BigDecimal getOccurrenceCuratorialExtensionId() {
        return this.occurrenceCuratorialExtensionId;
    }
    
    public void setOccurrenceCuratorialExtensionId(BigDecimal occurrenceCuratorialExtensionId) {
        this.occurrenceCuratorialExtensionId = occurrenceCuratorialExtensionId;
    }
    public Occurrence getOccurrence() {
        return this.occurrence;
    }
    
    public void setOccurrence(Occurrence occurrence) {
        this.occurrence = occurrence;
    }
    public String getCatalogNumberNumeric() {
        return this.catalogNumberNumeric;
    }
    
    public void setCatalogNumberNumeric(String catalogNumberNumeric) {
        this.catalogNumberNumeric = catalogNumberNumeric;
    }
    public String getIdentifiedBy() {
        return this.identifiedBy;
    }
    
    public void setIdentifiedBy(String identifiedBy) {
        this.identifiedBy = identifiedBy;
    }
    public String getDateIdentified() {
        return this.dateIdentified;
    }
    
    public void setDateIdentified(String dateIdentified) {
        this.dateIdentified = dateIdentified;
    }
    public String getCollectorNumber() {
        return this.collectorNumber;
    }
    
    public void setCollectorNumber(String collectorNumber) {
        this.collectorNumber = collectorNumber;
    }
    public String getFieldNumber() {
        return this.fieldNumber;
    }
    
    public void setFieldNumber(String fieldNumber) {
        this.fieldNumber = fieldNumber;
    }
    public String getFieldNotes() {
        return this.fieldNotes;
    }
    
    public void setFieldNotes(String fieldNotes) {
        this.fieldNotes = fieldNotes;
    }
    public String getVerbatimCollectingDate() {
        return this.verbatimCollectingDate;
    }
    
    public void setVerbatimCollectingDate(String verbatimCollectingDate) {
        this.verbatimCollectingDate = verbatimCollectingDate;
    }
    public String getVerbatimElevation() {
        return this.verbatimElevation;
    }
    
    public void setVerbatimElevation(String verbatimElevation) {
        this.verbatimElevation = verbatimElevation;
    }
    public String getVerbatimDepth() {
        return this.verbatimDepth;
    }
    
    public void setVerbatimDepth(String verbatimDepth) {
        this.verbatimDepth = verbatimDepth;
    }
    public String getPreparations() {
        return this.preparations;
    }
    
    public void setPreparations(String preparations) {
        this.preparations = preparations;
    }
    public String getTypeStatus() {
        return this.typeStatus;
    }
    
    public void setTypeStatus(String typeStatus) {
        this.typeStatus = typeStatus;
    }
    public String getGenBankNumber() {
        return this.genBankNumber;
    }
    
    public void setGenBankNumber(String genBankNumber) {
        this.genBankNumber = genBankNumber;
    }
    public String getOtherCatalogNumbers() {
        return this.otherCatalogNumbers;
    }
    
    public void setOtherCatalogNumbers(String otherCatalogNumbers) {
        this.otherCatalogNumbers = otherCatalogNumbers;
    }
    public String getRelatedCatalogItems() {
        return this.relatedCatalogItems;
    }
    
    public void setRelatedCatalogItems(String relatedCatalogItems) {
        this.relatedCatalogItems = relatedCatalogItems;
    }
    public String getDisposition() {
        return this.disposition;
    }
    
    public void setDisposition(String disposition) {
        this.disposition = disposition;
    }
    public String getIndividualCount() {
        return this.individualCount;
    }
    
    public void setIndividualCount(String individualCount) {
        this.individualCount = individualCount;
    }




}


