package org.inbio.neoportal.core.entity;
// Generated 02/05/2012 12:04:45 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.IndexedEmbedded;

/**
 * OccurrenceGeospatialExtension generated by hbm2java
 * @deprecated 
 */
public class OccurrenceGeospatialExtension  implements java.io.Serializable {


     @DocumentId
     private BigDecimal occurrenceGeospatialExtensionId;
     
     @ContainedIn
     private Occurrence occurrence;
     private String decimalLatitude;
     private String decimalLongitude;
     private String geodeticDatum;
     private String coordinateUncertaintyInMeters;
     private String pointRadiusSpatialFit;
     private String footprintWkt;
     private String footPrintSpatialFit;
     private String verbatimCoordinates;
     private String verbatimLatitude;
     private String verbatimLongitude;
     private String verbatimCoordinateSystem;
     private String georeferenceProtocol;
     private String georeferenceSources;
     private String georeferenceVerificationStatus;
     private String georeferenceRemarks;
     private Long locationId;
     
     @IndexedEmbedded(depth=1, prefix="feature_")
     private Set geoFeatures = new HashSet(0);

    public OccurrenceGeospatialExtension() {
    }

	
    public OccurrenceGeospatialExtension(BigDecimal occurrenceGeospatialExtensionId, Occurrence occurrence) {
        this.occurrenceGeospatialExtensionId = occurrenceGeospatialExtensionId;
        this.occurrence = occurrence;
    }
    public OccurrenceGeospatialExtension(BigDecimal occurrenceGeospatialExtensionId, Occurrence occurrence, String decimalLatitude, String decimalLongitude, String geodeticDatum, String coordinateUncertaintyInMeters, String pointRadiusSpatialFit, String footprintWkt, String footPrintSpatialFit, String verbatimCoordinates, String verbatimLatitude, String verbatimLongitude, String verbatimCoordinateSystem, String georeferenceProtocol, String georeferenceSources, String georeferenceVerificationStatus, String georeferenceRemarks, Long locationId, Set geoFeatures) {
       this.occurrenceGeospatialExtensionId = occurrenceGeospatialExtensionId;
       this.occurrence = occurrence;
       this.decimalLatitude = decimalLatitude;
       this.decimalLongitude = decimalLongitude;
       this.geodeticDatum = geodeticDatum;
       this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
       this.pointRadiusSpatialFit = pointRadiusSpatialFit;
       this.footprintWkt = footprintWkt;
       this.footPrintSpatialFit = footPrintSpatialFit;
       this.verbatimCoordinates = verbatimCoordinates;
       this.verbatimLatitude = verbatimLatitude;
       this.verbatimLongitude = verbatimLongitude;
       this.verbatimCoordinateSystem = verbatimCoordinateSystem;
       this.georeferenceProtocol = georeferenceProtocol;
       this.georeferenceSources = georeferenceSources;
       this.georeferenceVerificationStatus = georeferenceVerificationStatus;
       this.georeferenceRemarks = georeferenceRemarks;
       this.locationId = locationId;
       this.geoFeatures = geoFeatures;
    }
   
    public BigDecimal getOccurrenceGeospatialExtensionId() {
        return this.occurrenceGeospatialExtensionId;
    }
    
    public void setOccurrenceGeospatialExtensionId(BigDecimal occurrenceGeospatialExtensionId) {
        this.occurrenceGeospatialExtensionId = occurrenceGeospatialExtensionId;
    }
    public Occurrence getOccurrence() {
        return this.occurrence;
    }
    
    public void setOccurrence(Occurrence occurrence) {
        this.occurrence = occurrence;
    }
    public String getDecimalLatitude() {
        return this.decimalLatitude;
    }
    
    public void setDecimalLatitude(String decimalLatitude) {
        this.decimalLatitude = decimalLatitude;
    }
    public String getDecimalLongitude() {
        return this.decimalLongitude;
    }
    
    public void setDecimalLongitude(String decimalLongitude) {
        this.decimalLongitude = decimalLongitude;
    }
    public String getGeodeticDatum() {
        return this.geodeticDatum;
    }
    
    public void setGeodeticDatum(String geodeticDatum) {
        this.geodeticDatum = geodeticDatum;
    }
    public String getCoordinateUncertaintyInMeters() {
        return this.coordinateUncertaintyInMeters;
    }
    
    public void setCoordinateUncertaintyInMeters(String coordinateUncertaintyInMeters) {
        this.coordinateUncertaintyInMeters = coordinateUncertaintyInMeters;
    }
    public String getPointRadiusSpatialFit() {
        return this.pointRadiusSpatialFit;
    }
    
    public void setPointRadiusSpatialFit(String pointRadiusSpatialFit) {
        this.pointRadiusSpatialFit = pointRadiusSpatialFit;
    }
    public String getFootprintWkt() {
        return this.footprintWkt;
    }
    
    public void setFootprintWkt(String footprintWkt) {
        this.footprintWkt = footprintWkt;
    }
    public String getFootPrintSpatialFit() {
        return this.footPrintSpatialFit;
    }
    
    public void setFootPrintSpatialFit(String footPrintSpatialFit) {
        this.footPrintSpatialFit = footPrintSpatialFit;
    }
    public String getVerbatimCoordinates() {
        return this.verbatimCoordinates;
    }
    
    public void setVerbatimCoordinates(String verbatimCoordinates) {
        this.verbatimCoordinates = verbatimCoordinates;
    }
    public String getVerbatimLatitude() {
        return this.verbatimLatitude;
    }
    
    public void setVerbatimLatitude(String verbatimLatitude) {
        this.verbatimLatitude = verbatimLatitude;
    }
    public String getVerbatimLongitude() {
        return this.verbatimLongitude;
    }
    
    public void setVerbatimLongitude(String verbatimLongitude) {
        this.verbatimLongitude = verbatimLongitude;
    }
    public String getVerbatimCoordinateSystem() {
        return this.verbatimCoordinateSystem;
    }
    
    public void setVerbatimCoordinateSystem(String verbatimCoordinateSystem) {
        this.verbatimCoordinateSystem = verbatimCoordinateSystem;
    }
    public String getGeoreferenceProtocol() {
        return this.georeferenceProtocol;
    }
    
    public void setGeoreferenceProtocol(String georeferenceProtocol) {
        this.georeferenceProtocol = georeferenceProtocol;
    }
    public String getGeoreferenceSources() {
        return this.georeferenceSources;
    }
    
    public void setGeoreferenceSources(String georeferenceSources) {
        this.georeferenceSources = georeferenceSources;
    }
    public String getGeoreferenceVerificationStatus() {
        return this.georeferenceVerificationStatus;
    }
    
    public void setGeoreferenceVerificationStatus(String georeferenceVerificationStatus) {
        this.georeferenceVerificationStatus = georeferenceVerificationStatus;
    }
    public String getGeoreferenceRemarks() {
        return this.georeferenceRemarks;
    }
    
    public void setGeoreferenceRemarks(String georeferenceRemarks) {
        this.georeferenceRemarks = georeferenceRemarks;
    }
    public Long getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }
    public Set getGeoFeatures() {
        return this.geoFeatures;
    }
    
    public void setGeoFeatures(Set geoFeatures) {
        this.geoFeatures = geoFeatures;
    }




}


