package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ReferenceElement generated by hbm2java
 */
public class ReferenceElement  implements java.io.Serializable {


     private BigDecimal referenceElementId;
     private String name;
     private String label;
     private String description;
     private String guideLines;
     private String examples;
     private Set taxonHasReferenceElements = new HashSet(0);
     private Set occurrenceHasReferenceElements = new HashSet(0);
     private Set taxonDescriptionHasReferenceElements = new HashSet(0);
     private Set occurrenceHasReferenceElements_1 = new HashSet(0);

    public ReferenceElement() {
    }

	
    public ReferenceElement(BigDecimal referenceElementId) {
        this.referenceElementId = referenceElementId;
    }
    public ReferenceElement(BigDecimal referenceElementId, String name, String label, String description, String guideLines, String examples, Set taxonHasReferenceElements, Set occurrenceHasReferenceElements, Set taxonDescriptionHasReferenceElements, Set occurrenceHasReferenceElements_1) {
       this.referenceElementId = referenceElementId;
       this.name = name;
       this.label = label;
       this.description = description;
       this.guideLines = guideLines;
       this.examples = examples;
       this.taxonHasReferenceElements = taxonHasReferenceElements;
       this.occurrenceHasReferenceElements = occurrenceHasReferenceElements;
       this.taxonDescriptionHasReferenceElements = taxonDescriptionHasReferenceElements;
       this.occurrenceHasReferenceElements_1 = occurrenceHasReferenceElements_1;
    }
   
    public BigDecimal getReferenceElementId() {
        return this.referenceElementId;
    }
    
    public void setReferenceElementId(BigDecimal referenceElementId) {
        this.referenceElementId = referenceElementId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGuideLines() {
        return this.guideLines;
    }
    
    public void setGuideLines(String guideLines) {
        this.guideLines = guideLines;
    }
    public String getExamples() {
        return this.examples;
    }
    
    public void setExamples(String examples) {
        this.examples = examples;
    }
    public Set getTaxonHasReferenceElements() {
        return this.taxonHasReferenceElements;
    }
    
    public void setTaxonHasReferenceElements(Set taxonHasReferenceElements) {
        this.taxonHasReferenceElements = taxonHasReferenceElements;
    }
    public Set getOccurrenceHasReferenceElements() {
        return this.occurrenceHasReferenceElements;
    }
    
    public void setOccurrenceHasReferenceElements(Set occurrenceHasReferenceElements) {
        this.occurrenceHasReferenceElements = occurrenceHasReferenceElements;
    }
    public Set getTaxonDescriptionHasReferenceElements() {
        return this.taxonDescriptionHasReferenceElements;
    }
    
    public void setTaxonDescriptionHasReferenceElements(Set taxonDescriptionHasReferenceElements) {
        this.taxonDescriptionHasReferenceElements = taxonDescriptionHasReferenceElements;
    }
    public Set getOccurrenceHasReferenceElements_1() {
        return this.occurrenceHasReferenceElements_1;
    }
    
    public void setOccurrenceHasReferenceElements_1(Set occurrenceHasReferenceElements_1) {
        this.occurrenceHasReferenceElements_1 = occurrenceHasReferenceElements_1;
    }




}


