package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SearchGroup generated by hbm2java
 */
public class SearchGroup  implements java.io.Serializable {


     private BigDecimal searchGroupId;
     private String key;
     private Set searchFilters = new HashSet(0);
     private Set searchColumnDefaults = new HashSet(0);
     private Set searchColumns = new HashSet(0);
     
     public enum Group {
    	 TAXONOMIC, GEOGRAPHIC, SPECIMEN;
    	 
    	 @Override
    	 public String toString(){
    		 if(this.name() == "TAXONOMIC")
				return "taxonomic_information";
    		 else if(this.name() == "GEOGRAPHIC")
				return "geographic_information";
    		 else if(this.name() == "SPECIMEN")
				return "specimen_information";
    		 
    		 return "";
    	 }
     };

    public SearchGroup() {
    }

	
    public SearchGroup(BigDecimal searchGroupId, String key) {
        this.searchGroupId = searchGroupId;
        this.key = key;
    }
    public SearchGroup(BigDecimal searchGroupId, String key, Set searchFilters, Set searchColumnDefaults, Set searchColumns) {
       this.searchGroupId = searchGroupId;
       this.key = key;
       this.searchFilters = searchFilters;
       this.searchColumnDefaults = searchColumnDefaults;
       this.searchColumns = searchColumns;
    }
   
    public BigDecimal getSearchGroupId() {
        return this.searchGroupId;
    }
    
    public void setSearchGroupId(BigDecimal searchGroupId) {
        this.searchGroupId = searchGroupId;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public Set getSearchFilters() {
        return this.searchFilters;
    }
    
    public void setSearchFilters(Set searchFilters) {
        this.searchFilters = searchFilters;
    }
    public Set getSearchColumnDefaults() {
        return this.searchColumnDefaults;
    }
    
    public void setSearchColumnDefaults(Set searchColumnDefaults) {
        this.searchColumnDefaults = searchColumnDefaults;
    }
    public Set getSearchColumns() {
        return this.searchColumns;
    }
    
    public void setSearchColumns(Set searchColumns) {
        this.searchColumns = searchColumns;
    }




}


