package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * SearchColumnDefault generated by hbm2java
 */
public class SearchColumnDefault  implements java.io.Serializable {


     private BigDecimal columnDefaultId;
     private SearchGroup searchGroup;
     private String columnDefaultKey;

    public SearchColumnDefault() {
    }

	
    public SearchColumnDefault(BigDecimal columnDefaultId, SearchGroup searchGroup) {
        this.columnDefaultId = columnDefaultId;
        this.searchGroup = searchGroup;
    }
    public SearchColumnDefault(BigDecimal columnDefaultId, SearchGroup searchGroup, String columnDefaultKey) {
       this.columnDefaultId = columnDefaultId;
       this.searchGroup = searchGroup;
       this.columnDefaultKey = columnDefaultKey;
    }
   
    public BigDecimal getColumnDefaultId() {
        return this.columnDefaultId;
    }
    
    public void setColumnDefaultId(BigDecimal columnDefaultId) {
        this.columnDefaultId = columnDefaultId;
    }
    public SearchGroup getSearchGroup() {
        return this.searchGroup;
    }
    
    public void setSearchGroup(SearchGroup searchGroup) {
        this.searchGroup = searchGroup;
    }
    public String getColumnDefaultKey() {
        return this.columnDefaultKey;
    }
    
    public void setColumnDefaultKey(String columnDefaultKey) {
        this.columnDefaultKey = columnDefaultKey;
    }




}


