package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * SearchFilter generated by hbm2java
 */
public class SearchFilter  implements java.io.Serializable {


     private BigDecimal filterId;
     private SearchGroup searchGroup;
     private String filterKey;
     private String type;

    public SearchFilter() {
    }

	
    public SearchFilter(BigDecimal filterId) {
        this.filterId = filterId;
    }
    public SearchFilter(BigDecimal filterId, SearchGroup searchGroup, String filterKey, String type) {
       this.filterId = filterId;
       this.searchGroup = searchGroup;
       this.filterKey = filterKey;
       this.type = type;
    }
   
    public BigDecimal getFilterId() {
        return this.filterId;
    }
    
    public void setFilterId(BigDecimal filterId) {
        this.filterId = filterId;
    }
    public SearchGroup getSearchGroup() {
        return this.searchGroup;
    }
    
    public void setSearchGroup(SearchGroup searchGroup) {
        this.searchGroup = searchGroup;
    }
    public String getFilterKey() {
        return this.filterKey;
    }
    
    public void setFilterKey(String filterKey) {
        this.filterKey = filterKey;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


