/*
 *  NeoPortal - New implementation of the INBio Species and Occurrences portal.
 *  
 *  Copyright (C) 2010 INBio - Instituto Nacional de Biodiversidad, Costa Rica
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * Service generated by hbm2java
 */

public class Service  implements java.io.Serializable {


    // Fields    

     private BigDecimal serviceId;
     private String name;
     private String description;
     private String url;
     private String urlConnectionFormat;


    // Constructors

    /** default constructor */
    public Service() {
    }

	/** minimal constructor */
    public Service(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }
    
    /** full constructor */
    public Service(BigDecimal serviceId, String name, String description, String url, String urlConnectionFormat) {
        this.serviceId = serviceId;
        this.name = name;
        this.description = description;
        this.url = url;
        this.urlConnectionFormat = urlConnectionFormat;
    }
    

   
    // Property accessors

    public BigDecimal getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrlConnectionFormat() {
        return this.urlConnectionFormat;
    }
    
    public void setUrlConnectionFormat(String urlConnectionFormat) {
        this.urlConnectionFormat = urlConnectionFormat;
    }
   








}
