package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * Service generated by hbm2java
 */

public class Service  implements java.io.Serializable {


    // Fields    

     private BigDecimal serviceId;
     private String name;
     private String description;
     private String url;
     private String urlConnectionFormat;


    // Constructors

    /** default constructor */
    public Service() {
    }

	/** minimal constructor */
    public Service(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }
    
    /** full constructor */
    public Service(BigDecimal serviceId, String name, String description, String url, String urlConnectionFormat) {
        this.serviceId = serviceId;
        this.name = name;
        this.description = description;
        this.url = url;
        this.urlConnectionFormat = urlConnectionFormat;
    }
    

   
    // Property accessors

    public BigDecimal getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrlConnectionFormat() {
        return this.urlConnectionFormat;
    }
    
    public void setUrlConnectionFormat(String urlConnectionFormat) {
        this.urlConnectionFormat = urlConnectionFormat;
    }
   








}
