package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:44 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * TaxonHasAssociatedAttribute generated by hbm2java
 */

public class TaxonHasAssociatedAttribute  implements java.io.Serializable {


    // Fields    

     private TaxonHasAssociatedAttributeId id;
     private Taxon taxon;
     private AssociatedAttribute associatedAttribute;
     private String certaintyLevel;
     private String evaluationCriteria;
     private String regionality;
     private Set<TaxonAssociatedAttributeHasReferenceElement> taxonAssociatedAttributeHasReferenceElements = new HashSet<TaxonAssociatedAttributeHasReferenceElement>(0);


    // Constructors

    /** default constructor */
    public TaxonHasAssociatedAttribute() {
    }

	/** minimal constructor */
    public TaxonHasAssociatedAttribute(TaxonHasAssociatedAttributeId id, Taxon taxon, AssociatedAttribute associatedAttribute) {
        this.id = id;
        this.taxon = taxon;
        this.associatedAttribute = associatedAttribute;
    }
    
    /** full constructor */
    public TaxonHasAssociatedAttribute(TaxonHasAssociatedAttributeId id, Taxon taxon, AssociatedAttribute associatedAttribute, String certaintyLevel, String evaluationCriteria, String regionality, Set<TaxonAssociatedAttributeHasReferenceElement> taxonAssociatedAttributeHasReferenceElements) {
        this.id = id;
        this.taxon = taxon;
        this.associatedAttribute = associatedAttribute;
        this.certaintyLevel = certaintyLevel;
        this.evaluationCriteria = evaluationCriteria;
        this.regionality = regionality;
        this.taxonAssociatedAttributeHasReferenceElements = taxonAssociatedAttributeHasReferenceElements;
    }
    

   
    // Property accessors

    public TaxonHasAssociatedAttributeId getId() {
        return this.id;
    }
    
    public void setId(TaxonHasAssociatedAttributeId id) {
        this.id = id;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }

    public AssociatedAttribute getAssociatedAttribute() {
        return this.associatedAttribute;
    }
    
    public void setAssociatedAttribute(AssociatedAttribute associatedAttribute) {
        this.associatedAttribute = associatedAttribute;
    }

    public String getCertaintyLevel() {
        return this.certaintyLevel;
    }
    
    public void setCertaintyLevel(String certaintyLevel) {
        this.certaintyLevel = certaintyLevel;
    }

    public String getEvaluationCriteria() {
        return this.evaluationCriteria;
    }
    
    public void setEvaluationCriteria(String evaluationCriteria) {
        this.evaluationCriteria = evaluationCriteria;
    }

    public String getRegionality() {
        return this.regionality;
    }
    
    public void setRegionality(String regionality) {
        this.regionality = regionality;
    }

    public Set<TaxonAssociatedAttributeHasReferenceElement> getTaxonAssociatedAttributeHasReferenceElements() {
        return this.taxonAssociatedAttributeHasReferenceElements;
    }
    
    public void setTaxonAssociatedAttributeHasReferenceElements(Set<TaxonAssociatedAttributeHasReferenceElement> taxonAssociatedAttributeHasReferenceElements) {
        this.taxonAssociatedAttributeHasReferenceElements = taxonAssociatedAttributeHasReferenceElements;
    }
   








}
