package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TaxonHasAssociatedAttribute generated by hbm2java
 */
public class TaxonHasAssociatedAttribute  implements java.io.Serializable {


     private TaxonHasAssociatedAttributeId id;
     private Taxon taxon;
     private AssociatedAttribute associatedAttribute;
     private String certaintyLevel;
     private String evaluationCriteria;
     private String regionality;
     private Set taxonAssociatedAttributeHasReferenceElements = new HashSet(0);

    public TaxonHasAssociatedAttribute() {
    }

	
    public TaxonHasAssociatedAttribute(TaxonHasAssociatedAttributeId id, Taxon taxon, AssociatedAttribute associatedAttribute) {
        this.id = id;
        this.taxon = taxon;
        this.associatedAttribute = associatedAttribute;
    }
    public TaxonHasAssociatedAttribute(TaxonHasAssociatedAttributeId id, Taxon taxon, AssociatedAttribute associatedAttribute, String certaintyLevel, String evaluationCriteria, String regionality, Set taxonAssociatedAttributeHasReferenceElements) {
       this.id = id;
       this.taxon = taxon;
       this.associatedAttribute = associatedAttribute;
       this.certaintyLevel = certaintyLevel;
       this.evaluationCriteria = evaluationCriteria;
       this.regionality = regionality;
       this.taxonAssociatedAttributeHasReferenceElements = taxonAssociatedAttributeHasReferenceElements;
    }
   
    public TaxonHasAssociatedAttributeId getId() {
        return this.id;
    }
    
    public void setId(TaxonHasAssociatedAttributeId id) {
        this.id = id;
    }
    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }
    public AssociatedAttribute getAssociatedAttribute() {
        return this.associatedAttribute;
    }
    
    public void setAssociatedAttribute(AssociatedAttribute associatedAttribute) {
        this.associatedAttribute = associatedAttribute;
    }
    public String getCertaintyLevel() {
        return this.certaintyLevel;
    }
    
    public void setCertaintyLevel(String certaintyLevel) {
        this.certaintyLevel = certaintyLevel;
    }
    public String getEvaluationCriteria() {
        return this.evaluationCriteria;
    }
    
    public void setEvaluationCriteria(String evaluationCriteria) {
        this.evaluationCriteria = evaluationCriteria;
    }
    public String getRegionality() {
        return this.regionality;
    }
    
    public void setRegionality(String regionality) {
        this.regionality = regionality;
    }
    public Set getTaxonAssociatedAttributeHasReferenceElements() {
        return this.taxonAssociatedAttributeHasReferenceElements;
    }
    
    public void setTaxonAssociatedAttributeHasReferenceElements(Set taxonAssociatedAttributeHasReferenceElements) {
        this.taxonAssociatedAttributeHasReferenceElements = taxonAssociatedAttributeHasReferenceElements;
    }




}


