/*
 *  NeoPortal - New implementation of the INBio Species and Occurrences portal.
 *  
 *  Copyright (C) 2010 INBio - Instituto Nacional de Biodiversidad, Costa Rica
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.io.UnsupportedEncodingException;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.Store;

/**
 * TaxonDescription generated by hbm2java
 * @author asanabria
 */
@Indexed
public class TaxonDescription  
    implements java.io.Serializable {


    // Fields    

    @DocumentId
     private BigDecimal taxonDescriptionId;
     private String version;
     private DataProvider dataProvider;

     @ContainedIn
     private Taxon taxon;
     private String globalUniqueIdentifier;
     @Field
     private String scientificName;
     private String institutionCode;
     private Date dateLastModified;
     private String taxonRecordId;
     private String language;
     private String creators;
     private String distribution;
     private String abstract_;

     @Field
     private String kingdomTaxon;

     @Field
     private String phylumTaxon;

     @Field
     private String classTaxon;

     @Field
     private String orderTaxon;

     @Field
     private String familyTaxon;

     @Field
     private String genusTaxon;

     @Field
     private String synonyms;
     private String authorYearOfScientificName;
     private String speciesPublicationReference;

     @Field (store=Store.YES)
     private String commonNames;
     private String typification;
     private String contributors;
     private Date dateCreated;
     private String habit;
     private String lifeCycle;
     private String reproduction;
     private String annualCycle;
     private String scientificDescription;
     private String briefDescription;
     private String feeding;
     private String behavior;
     private String interactions;
     private String chromosomicNumberN;
     private String molecularData;
     private String populationBiology;
     private String threatStatus;
     private String legislation;
     private String habitat;
     private String territory;
     private String endemicity;
     private String theUses;
     private String theManagement;
     private String folklore;
     private String theReferences;
     private String unstructuredDocumentation;
     private String otherInformationSources;
     private String papers;
     private String identificationKeys;
     private String migratoryData;
     private String ecologicalSignificance;
     private String unstructuredNaturalHistory;
     private String invasivenessData;
     private String targetAudiences;
     private Set taxonDescriptionHasReferenceElements = new HashSet(0);

    public TaxonDescription() {
    }

	
    public TaxonDescription(BigDecimal taxonDescriptionId, DataProvider dataProvider, Taxon taxon) {
        this.taxonDescriptionId = taxonDescriptionId;
        this.dataProvider = dataProvider;
        this.taxon = taxon;
    }
    public TaxonDescription(BigDecimal taxonDescriptionId, Taxon taxon, DataProvider dataProvider, String globalUniqueIdentifier, String scientificName, String institutionCode, Date dateLastModified, String taxonRecordId, String language, String creators, String distribution, String abstract_, String kingdomTaxon, String phylumTaxon, String classTaxon, String orderTaxon, String familyTaxon, String genusTaxon, String synonyms, String authorYearOfScientificName, String speciesPublicationReference, String commonNames, String typification, String contributors, Date dateCreated, String habit, String lifeCycle, String reproduction, String annualCycle, String scientificDescription, String briefDescription, String feeding, String behavior, String interactions, String chromosomicNumberN, String molecularData, String populationBiology, String threatStatus, String legislation, String habitat, String territory, String endemicity, String theUses, String theManagement, String folklore, String theReferences, String unstructuredDocumentation, String otherInformationSources, String papers, String identificationKeys, String migratoryData, String ecologicalSignificance, String unstructuredNaturalHistory, String invasivenessData, String targetAudiences, Set taxonDescriptionHasReferenceElements) {
       this.taxonDescriptionId = taxonDescriptionId;
       this.taxon = taxon;
       this.dataProvider = dataProvider;
       this.globalUniqueIdentifier = globalUniqueIdentifier;
       this.scientificName = scientificName;
       this.institutionCode = institutionCode;
       this.dateLastModified = dateLastModified;
       this.taxonRecordId = taxonRecordId;
       this.language = language;
       this.creators = creators;
       this.distribution = distribution;
       this.abstract_ = abstract_;
       this.kingdomTaxon = kingdomTaxon;
       this.phylumTaxon = phylumTaxon;
       this.classTaxon = classTaxon;
       this.orderTaxon = orderTaxon;
       this.familyTaxon = familyTaxon;
       this.genusTaxon = genusTaxon;
       this.synonyms = synonyms;
       this.authorYearOfScientificName = authorYearOfScientificName;
       this.speciesPublicationReference = speciesPublicationReference;
       this.commonNames = commonNames;
       this.typification = typification;
       this.contributors = contributors;
       this.dateCreated = dateCreated;
       this.habit = habit;
       this.lifeCycle = lifeCycle;
       this.reproduction = reproduction;
       this.annualCycle = annualCycle;
       this.scientificDescription = scientificDescription;
       this.briefDescription = briefDescription;
       this.feeding = feeding;
       this.behavior = behavior;
       this.interactions = interactions;
       this.chromosomicNumberN = chromosomicNumberN;
       this.molecularData = molecularData;
       this.populationBiology = populationBiology;
       this.threatStatus = threatStatus;
       this.legislation = legislation;
       this.habitat = habitat;
       this.territory = territory;
       this.endemicity = endemicity;
       this.theUses = theUses;
       this.theManagement = theManagement;
       this.folklore = folklore;
       this.theReferences = theReferences;
       this.unstructuredDocumentation = unstructuredDocumentation;
       this.otherInformationSources = otherInformationSources;
       this.papers = papers;
       this.identificationKeys = identificationKeys;
       this.migratoryData = migratoryData;
       this.ecologicalSignificance = ecologicalSignificance;
       this.unstructuredNaturalHistory = unstructuredNaturalHistory;
       this.invasivenessData = invasivenessData;
       this.targetAudiences = targetAudiences;
       this.taxonDescriptionHasReferenceElements = taxonDescriptionHasReferenceElements;
    }
   
    public BigDecimal getTaxonDescriptionId() {
        return this.taxonDescriptionId;
    }
    
    public void setTaxonDescriptionId(BigDecimal taxonDescriptionId) {
        this.taxonDescriptionId = taxonDescriptionId;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    public DataProvider getDataProvider() {
        return this.dataProvider;
    }
    
    public void setDataProvider(DataProvider dataProvider) {
        this.dataProvider = dataProvider;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }
    
    public String getGlobalUniqueIdentifier() {
        return this.globalUniqueIdentifier;
    }
    
    public void setGlobalUniqueIdentifier(String globalUniqueIdentifier) {
        this.globalUniqueIdentifier = globalUniqueIdentifier;
    }
    public String getScientificName() {
        return this.scientificName;
    }
    
    public void setScientificName(String scientificName) {
        this.scientificName = scientificName;
    }
    public String getInstitutionCode() {
        return this.institutionCode;
    }
    
    public void setInstitutionCode(String institutionCode) {
        this.institutionCode = institutionCode;
    }
    public Date getDateLastModified() {
        return this.dateLastModified;
    }
    
    public void setDateLastModified(Date dateLastModified) {
        this.dateLastModified = dateLastModified;
    }
    public String getTaxonRecordId() {
        return this.taxonRecordId;
    }
    
    public void setTaxonRecordId(String taxonRecordId) {
        this.taxonRecordId = taxonRecordId;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getCreators() {
        return this.creators;
    }
    
    public void setCreators(String creators) {
        this.creators = creators;
    }
    public String getDistribution() {
        return this.distribution;
    }
    
    public void setDistribution(String distribution) {
        this.distribution = distribution;
    }
    public String getAbstract_() {
        return this.abstract_;
    }
    
    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }
    public String getKingdomTaxon() {
        return this.kingdomTaxon;
    }
    
    public void setKingdomTaxon(String kingdomTaxon) {
        this.kingdomTaxon = kingdomTaxon;
    }
    public String getPhylumTaxon() {
        return this.phylumTaxon;
    }
    
    public void setPhylumTaxon(String phylumTaxon) {
        this.phylumTaxon = phylumTaxon;
    }
    public String getClassTaxon() {
        return this.classTaxon;
    }
    
    public void setClassTaxon(String classTaxon) {
        this.classTaxon = classTaxon;
    }
    public String getOrderTaxon() {
        return this.orderTaxon;
    }
    
    public void setOrderTaxon(String orderTaxon) {
        this.orderTaxon = orderTaxon;
    }
    public String getFamilyTaxon() {
        return this.familyTaxon;
    }
    
    public void setFamilyTaxon(String familyTaxon) {
        this.familyTaxon = familyTaxon;
    }
    public String getGenusTaxon() {
        return this.genusTaxon;
    }
    
    public void setGenusTaxon(String genusTaxon) {
        this.genusTaxon = genusTaxon;
    }
    public String getSynonyms() {
        return this.synonyms;
    }
    
    public void setSynonyms(String synonyms) throws UnsupportedEncodingException {
        //byte[] utf8Bytes = synonyms.getBytes("UTF8");
        this.synonyms = synonyms != null? synonyms.replaceAll("\u000b"," ") : "";
        //this.synonyms = synonyms;
    }
    public String getAuthorYearOfScientificName() {
        return this.authorYearOfScientificName;
    }
    
    public void setAuthorYearOfScientificName(String authorYearOfScientificName) {
        this.authorYearOfScientificName = authorYearOfScientificName;
    }
    public String getSpeciesPublicationReference() {
        return this.speciesPublicationReference;
    }
    
    public void setSpeciesPublicationReference(String speciesPublicationReference) {
        this.speciesPublicationReference = speciesPublicationReference;
    }
    public String getCommonNames() {
        return this.commonNames;
    }
    
    public void setCommonNames(String commonNames) {
        this.commonNames = commonNames != null? commonNames.replaceAll("\u000b"," ") : "";
    }
    public String getTypification() {
        return this.typification;
    }
    
    public void setTypification(String typification) {
        this.typification = typification;
    }
    public String getContributors() {
        return this.contributors;
    }
    
    public void setContributors(String contributors) {
        this.contributors = contributors;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getHabit() {
        return this.habit;
    }
    
    public void setHabit(String habit) {
        this.habit = habit;
    }
    public String getLifeCycle() {
        return this.lifeCycle;
    }
    
    public void setLifeCycle(String lifeCycle) {
        this.lifeCycle = lifeCycle != null? lifeCycle.replaceAll("\u000b"," ") : "";
    }
    public String getReproduction() {
        return this.reproduction;
    }
    
    public void setReproduction(String reproduction) {
        this.reproduction = reproduction;
    }
    public String getAnnualCycle() {
        return this.annualCycle;
    }
    
    public void setAnnualCycle(String annualCycle) {
        this.annualCycle = annualCycle;
    }
    public String getScientificDescription() {
        return this.scientificDescription;
    }
    
    public void setScientificDescription(String scientificDescription) {
        this.scientificDescription = scientificDescription;
    }
    public String getBriefDescription() {
        return this.briefDescription;
    }
    
    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
    }
    public String getFeeding() {
        return this.feeding;
    }
    
    public void setFeeding(String feeding) {
        this.feeding = feeding;
    }
    public String getBehavior() {
        return this.behavior;
    }
    
    public void setBehavior(String behavior) {
        this.behavior = behavior;
    }
    public String getInteractions() {
        return this.interactions;
    }
    
    public void setInteractions(String interactions) {
        this.interactions = interactions;
    }
    public String getChromosomicNumberN() {
        return this.chromosomicNumberN;
    }
    
    public void setChromosomicNumberN(String chromosomicNumberN) {
        this.chromosomicNumberN = chromosomicNumberN;
    }
    public String getMolecularData() {
        return this.molecularData;
    }
    
    public void setMolecularData(String molecularData) {
        this.molecularData = molecularData;
    }
    public String getPopulationBiology() {
        return this.populationBiology;
    }
    
    public void setPopulationBiology(String populationBiology) {
        this.populationBiology = populationBiology != null? populationBiology.replaceAll("\u000b", " ") : "";
    }
    public String getThreatStatus() {
        return this.threatStatus;
    }
    
    public void setThreatStatus(String threatStatus) {
        this.threatStatus = threatStatus;
    }
    public String getLegislation() {
        return this.legislation;
    }
    
    public void setLegislation(String legislation) {
        this.legislation = legislation;
    }
    public String getHabitat() {
        return this.habitat ;
    }
    
    public void setHabitat(String habitat) {
        this.habitat = habitat != null? habitat.replaceAll("\u000b", " ") : "";
    }
    public String getTerritory() {
        return this.territory;
    }
    
    public void setTerritory(String territory) {
        this.territory = territory;
    }
    public String getEndemicity() {
        return this.endemicity;
    }
    
    public void setEndemicity(String endemicity) {
        this.endemicity = endemicity;
    }
    public String getTheUses() {
        return this.theUses;
    }
    
    public void setTheUses(String theUses) {
        this.theUses = theUses;
    }
    public String getTheManagement() {
        return this.theManagement;
    }
    
    public void setTheManagement(String theManagement) {
        this.theManagement = theManagement;
    }
    public String getFolklore() {
        return this.folklore;
    }
    
    public void setFolklore(String folklore) {
        this.folklore = folklore != null? folklore.replaceAll("\u000b", " ") : "";
    }
    public String getTheReferences() {
        return this.theReferences;
    }
    
    public void setTheReferences(String theReferences) {
        this.theReferences = theReferences;
    }
    public String getUnstructuredDocumentation() {
        return this.unstructuredDocumentation;
    }
    
    public void setUnstructuredDocumentation(String unstructuredDocumentation) {
        this.unstructuredDocumentation = unstructuredDocumentation;
    }
    public String getOtherInformationSources() {
        return this.otherInformationSources;
    }
    
    public void setOtherInformationSources(String otherInformationSources) {
        this.otherInformationSources = otherInformationSources;
    }
    public String getPapers() {
        return this.papers;
    }
    
    public void setPapers(String papers) {
        this.papers = papers;
    }
    public String getIdentificationKeys() {
        return this.identificationKeys;
    }
    
    public void setIdentificationKeys(String identificationKeys) {
        this.identificationKeys = identificationKeys;
    }
    public String getMigratoryData() {
        return this.migratoryData;
    }
    
    public void setMigratoryData(String migratoryData) {
        this.migratoryData = migratoryData;
    }
    public String getEcologicalSignificance() {
        return this.ecologicalSignificance;
    }
    
    public void setEcologicalSignificance(String ecologicalSignificance) {
        this.ecologicalSignificance = ecologicalSignificance;
    }
    public String getUnstructuredNaturalHistory() {
        return this.unstructuredNaturalHistory;
    }
    
    public void setUnstructuredNaturalHistory(String unstructuredNaturalHistory) {
        this.unstructuredNaturalHistory = unstructuredNaturalHistory;
    }
    public String getInvasivenessData() {
        return this.invasivenessData;
    }
    
    public void setInvasivenessData(String invasivenessData) {
        this.invasivenessData = invasivenessData;
    }
    public String getTargetAudiences() {
        return this.targetAudiences;
    }
    
    public void setTargetAudiences(String targetAudiences) {
        this.targetAudiences = targetAudiences;
    }
    public Set getTaxonDescriptionHasReferenceElements() {
        return this.taxonDescriptionHasReferenceElements;
    }
    
    public void setTaxonDescriptionHasReferenceElements(Set taxonDescriptionHasReferenceElements) {
        this.taxonDescriptionHasReferenceElements = taxonDescriptionHasReferenceElements;
    }




}


