package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * TaxonDescriptionHasReferenceElementId generated by hbm2java
 */

public class TaxonDescriptionHasReferenceElementId  implements java.io.Serializable {


    // Fields    

     private BigDecimal taxonDescriptionId;
     private BigDecimal referenceElementId;


    // Constructors

    /** default constructor */
    public TaxonDescriptionHasReferenceElementId() {
    }

    
    /** full constructor */
    public TaxonDescriptionHasReferenceElementId(BigDecimal taxonDescriptionId, BigDecimal referenceElementId) {
        this.taxonDescriptionId = taxonDescriptionId;
        this.referenceElementId = referenceElementId;
    }
    

   
    // Property accessors

    public BigDecimal getTaxonDescriptionId() {
        return this.taxonDescriptionId;
    }
    
    public void setTaxonDescriptionId(BigDecimal taxonDescriptionId) {
        this.taxonDescriptionId = taxonDescriptionId;
    }

    public BigDecimal getReferenceElementId() {
        return this.referenceElementId;
    }
    
    public void setReferenceElementId(BigDecimal referenceElementId) {
        this.referenceElementId = referenceElementId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxonDescriptionHasReferenceElementId) ) return false;
		 TaxonDescriptionHasReferenceElementId castOther = ( TaxonDescriptionHasReferenceElementId ) other; 
         
		 return ( (this.getTaxonDescriptionId()==castOther.getTaxonDescriptionId()) || ( this.getTaxonDescriptionId()!=null && castOther.getTaxonDescriptionId()!=null && this.getTaxonDescriptionId().equals(castOther.getTaxonDescriptionId()) ) )
 && ( (this.getReferenceElementId()==castOther.getReferenceElementId()) || ( this.getReferenceElementId()!=null && castOther.getReferenceElementId()!=null && this.getReferenceElementId().equals(castOther.getReferenceElementId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxonDescriptionId() == null ? 0 : this.getTaxonDescriptionId().hashCode() );
         result = 37 * result + ( getReferenceElementId() == null ? 0 : this.getReferenceElementId().hashCode() );
         return result;
   }   





}
