/*
 *  NeoPortal - New implementation of the INBio Species and Occurrences portal.
 *  
 *  Copyright (C) 2010 INBio - Instituto Nacional de Biodiversidad, Costa Rica
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:44 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * TaxonHasAssociatedAttribute generated by hbm2java
 * @author asanabria
 */

public class TaxonHasAssociatedAttribute  implements java.io.Serializable {


    // Fields    

     private TaxonHasAssociatedAttributeId id;
     private Taxon taxon;
     private AssociatedAttribute associatedAttribute;
     private String certaintyLevel;
     private String evaluationCriteria;
     private String regionality;
     private Set<TaxonAssociatedAttributeHasReferenceElement> 
         taxonAssociatedAttributeHasReferenceElements 
            = new HashSet<TaxonAssociatedAttributeHasReferenceElement>(0);


    // Constructors

    /** default constructor */
    public TaxonHasAssociatedAttribute() {
    }

	/** minimal constructor */
    public TaxonHasAssociatedAttribute(TaxonHasAssociatedAttributeId id, 
        Taxon taxon, AssociatedAttribute associatedAttribute) {
        
        this.id = id;
        this.taxon = taxon;
        this.associatedAttribute = associatedAttribute;
    }
    
    /** full constructor */
    public TaxonHasAssociatedAttribute(
        TaxonHasAssociatedAttributeId id,
        Taxon taxon, AssociatedAttribute associatedAttribute, 
        String certaintyLevel, String evaluationCriteria, String regionality, 
        Set<TaxonAssociatedAttributeHasReferenceElement> taxonAssociatedAttributeHasReferenceElements) {
        
        this.id = id;
        this.taxon = taxon;
        this.associatedAttribute = associatedAttribute;
        this.certaintyLevel = certaintyLevel;
        this.evaluationCriteria = evaluationCriteria;
        this.regionality = regionality;
        this.taxonAssociatedAttributeHasReferenceElements 
            = taxonAssociatedAttributeHasReferenceElements;
    }
    

   
    // Property accessors

    public TaxonHasAssociatedAttributeId getId() {
        return this.id;
    }
    
    public void setId(TaxonHasAssociatedAttributeId id) {
        this.id = id;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }

    public AssociatedAttribute getAssociatedAttribute() {
        return this.associatedAttribute;
    }
    
    public void setAssociatedAttribute(AssociatedAttribute associatedAttribute) {
        this.associatedAttribute = associatedAttribute;
    }

    public String getCertaintyLevel() {
        return this.certaintyLevel;
    }
    
    public void setCertaintyLevel(String certaintyLevel) {
        this.certaintyLevel = certaintyLevel;
    }

    public String getEvaluationCriteria() {
        return this.evaluationCriteria;
    }
    
    public void setEvaluationCriteria(String evaluationCriteria) {
        this.evaluationCriteria = evaluationCriteria;
    }

    public String getRegionality() {
        return this.regionality;
    }
    
    public void setRegionality(String regionality) {
        this.regionality = regionality;
    }

    public Set<TaxonAssociatedAttributeHasReferenceElement> 
        getTaxonAssociatedAttributeHasReferenceElements() {
        
        return this.taxonAssociatedAttributeHasReferenceElements;
    }
    
    public void setTaxonAssociatedAttributeHasReferenceElements(
        Set<TaxonAssociatedAttributeHasReferenceElement> taxonAssociatedAttributeHasReferenceElements) {
        
        this.taxonAssociatedAttributeHasReferenceElements 
            = taxonAssociatedAttributeHasReferenceElements;
    }
   








}
