package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4



/**
 * TaxonDescriptionHasReferenceElement generated by hbm2java
 */

public class TaxonDescriptionHasReferenceElement  implements java.io.Serializable {


    // Fields    

     private TaxonDescriptionHasReferenceElementId id;
     private ReferenceElement referenceElement;
     private TaxonDescription taxonDescription;
     private String value;


    // Constructors

    /** default constructor */
    public TaxonDescriptionHasReferenceElement() {
    }

	/** minimal constructor */
    public TaxonDescriptionHasReferenceElement(TaxonDescriptionHasReferenceElementId id, ReferenceElement referenceElement, TaxonDescription taxonDescription) {
        this.id = id;
        this.referenceElement = referenceElement;
        this.taxonDescription = taxonDescription;
    }
    
    /** full constructor */
    public TaxonDescriptionHasReferenceElement(TaxonDescriptionHasReferenceElementId id, ReferenceElement referenceElement, TaxonDescription taxonDescription, String value) {
        this.id = id;
        this.referenceElement = referenceElement;
        this.taxonDescription = taxonDescription;
        this.value = value;
    }
    

   
    // Property accessors

    public TaxonDescriptionHasReferenceElementId getId() {
        return this.id;
    }
    
    public void setId(TaxonDescriptionHasReferenceElementId id) {
        this.id = id;
    }

    public ReferenceElement getReferenceElement() {
        return this.referenceElement;
    }
    
    public void setReferenceElement(ReferenceElement referenceElement) {
        this.referenceElement = referenceElement;
    }

    public TaxonDescription getTaxonDescription() {
        return this.taxonDescription;
    }
    
    public void setTaxonDescription(TaxonDescription taxonDescription) {
        this.taxonDescription = taxonDescription;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}
