package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA



/**
 * TaxonDescriptionHasReferenceElement generated by hbm2java
 */
public class TaxonDescriptionHasReferenceElement  implements java.io.Serializable {


     private TaxonDescriptionHasReferenceElementId id;
     private ReferenceElement referenceElement;
     private TaxonDescription taxonDescription;
     private String value;

    public TaxonDescriptionHasReferenceElement() {
    }

	
    public TaxonDescriptionHasReferenceElement(TaxonDescriptionHasReferenceElementId id, ReferenceElement referenceElement, TaxonDescription taxonDescription) {
        this.id = id;
        this.referenceElement = referenceElement;
        this.taxonDescription = taxonDescription;
    }
    public TaxonDescriptionHasReferenceElement(TaxonDescriptionHasReferenceElementId id, ReferenceElement referenceElement, TaxonDescription taxonDescription, String value) {
       this.id = id;
       this.referenceElement = referenceElement;
       this.taxonDescription = taxonDescription;
       this.value = value;
    }
   
    public TaxonDescriptionHasReferenceElementId getId() {
        return this.id;
    }
    
    public void setId(TaxonDescriptionHasReferenceElementId id) {
        this.id = id;
    }
    public ReferenceElement getReferenceElement() {
        return this.referenceElement;
    }
    
    public void setReferenceElement(ReferenceElement referenceElement) {
        this.referenceElement = referenceElement;
    }
    public TaxonDescription getTaxonDescription() {
        return this.taxonDescription;
    }
    
    public void setTaxonDescription(TaxonDescription taxonDescription) {
        this.taxonDescription = taxonDescription;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


