package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA



/**
 * TaxonHasReferenceElement generated by hbm2java
 */
public class TaxonHasReferenceElement  implements java.io.Serializable {


     private TaxonHasReferenceElementId id;
     private Taxon taxon;
     private ReferenceElement referenceElement;
     private String value;

    public TaxonHasReferenceElement() {
    }

	
    public TaxonHasReferenceElement(TaxonHasReferenceElementId id, Taxon taxon, ReferenceElement referenceElement) {
        this.id = id;
        this.taxon = taxon;
        this.referenceElement = referenceElement;
    }
    public TaxonHasReferenceElement(TaxonHasReferenceElementId id, Taxon taxon, ReferenceElement referenceElement, String value) {
       this.id = id;
       this.taxon = taxon;
       this.referenceElement = referenceElement;
       this.value = value;
    }
   
    public TaxonHasReferenceElementId getId() {
        return this.id;
    }
    
    public void setId(TaxonHasReferenceElementId id) {
        this.id = id;
    }
    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }
    public ReferenceElement getReferenceElement() {
        return this.referenceElement;
    }
    
    public void setReferenceElement(ReferenceElement referenceElement) {
        this.referenceElement = referenceElement;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


