package org.inbio.neoportal.core.entity;
// Generated 01/07/2014 05:24:58 PM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * TaxonPlic generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class TaxonPlic implements java.io.Serializable {


  private BigDecimal taxonRecordId;
  private BigDecimal version;
  private String scientificName;
  private String scientificNameAuthorship;
  private String namePublishedInYear; // publicacion
  private String individualName;
  private String dateIssued;
  private String commonNamesUnstructured;
  private String synonyms;// sinonimo
  private String typeLocality;// localidad
  private String typeDepository;
  private String fullDescriptionUnstructured;
  private String molecularDataUnstructure;
  private String crDistribution;
  private String regionalDistribution;
  private String annualCyclesUnstructure;
  private String collectingMethod;
  private String usesUnstructure;
  private String myths;
  private String lifeCycleUnstructure;
  private String interactionUnstructure;
  private String lifeFormUnstructure;
  private String reproductionUnstructure;
  private String populationBiologyUnstructure;
  private String demographyUnstructure;
  private String threatUnstructure;
  private String references;
  private String urlfigure1;
  private String urldescriptionfigure;
  private String published;
  private String urldistributionmap;
  private String urlfigure2;
  private String urlfigure3;
  private String captiondescriptionfigure;
  private String idversionanterior;
  private String hasversion;
  private String colaborator1;
  private String colaborator2;
  private String captionfigure1;
  private String captionfigure2;
  private String captionfigure3;
  private String family;
  private String genus;
  private String order;
  private String publishedin;
  private String typecollector;
  private String habitatUnstructure;
  private String territoryUnstructure;
  private String feedingUnstructure;
  private String captiondistributionmap;
  private String phenologyUnstructure;
  private String conservationareadistribution;
  private String visible;
  private String coauthor1;
  private String coauthor2;
  private String emailauthor;
  private String behaviorUnstructure;
  private String urlthumbnail;
  private String creationdate;
  private String modificationdate;
  private String createdby;
  private String lastmodificationby;
  private String threatStatus;
  private String recordurl;
  private String urllogo1;
  private String urllogo2;
  private String speciesrecordstatus;
  private String philologist;
  private String subfamily;
  private String language;
  private String esMetaDescriptors;
  private String enMetaDescriptors;
  private String species;
  private String citesThreatStatus;
  private String uicnThreatStatus;
  private String wildProtectedAreaDistribution;
  private String etymology;
  private String urlvideo;
  private Set <Book> books = new HashSet<Book>(0);
  
 
  @JsonIgnore
  private Taxon  taxon;

  public TaxonPlic() {}


  public TaxonPlic(BigDecimal taxonRecordId) {
    this.taxonRecordId = taxonRecordId;
  }

  public TaxonPlic(BigDecimal taxonRecordId, String scientificName,
      String scientificNameAuthorship, String namePublishedInYear, String individualName,
      String dateIssued, String commonNamesUnstructured, String synonyms, String typeLocality,
      String typeDepository, String fullDescriptionUnstructured, String molecularDataUnstructure,
      String crDistribution, String regionalDistribution, String annualCyclesUnstructure,
      String collectingMethod, String usesUnstructure, String myths, String lifeCycleUnstructure,
      String interactionUnstructure, String lifeFormUnstructure, String reproductionUnstructure,
      String populationBiologyUnstructure, String demographyUnstructure, String threatUnstructure,
      String references, String urlfigure1, String urldescriptionfigure, String published,
      String urldistributionmap, String urlfigure2, String urlfigure3,
      String captiondescriptionfigure, String idversionanterior, String hasversion,
      String colaborator1, String colaborator2, String captionfigure1, String captionfigure2,
      String captionfigure3, String family, String genus, String order, String publishedin,
      String typecollector, String habitatUnstructure, String territoryUnstructure,
      String feedingUnstructure, String captiondistributionmap, String phenologyUnstructure,
      String conservationareadistribution, String visible, String coauthor1, String coauthor2,
      String emailauthor, String behaviorUnstructure, String urlthumbnail, String creationdate,
      String modificationdate, String createdby, String lastmodificationby, String threatStatus,
      String recordurl, String urllogo1, String urllogo2, String speciesrecordstatus,
      String philologist, String subfamily, String language, String esMetaDescriptors,
      String enMetaDescriptors, String species, String citesThreatStatus, String uicnThreatStatus,
      String wildProtectedAreaDistribution, String etymology, String urlvideo, Taxon taxon, String ConservationAreaDistribution , Set<Book> books) {
    this.taxonRecordId = taxonRecordId;
    this.scientificName = scientificName;
    this.scientificNameAuthorship = scientificNameAuthorship;
    this.namePublishedInYear = namePublishedInYear;
    this.individualName = individualName;
    this.dateIssued = dateIssued;
    this.commonNamesUnstructured = commonNamesUnstructured;
    this.synonyms = synonyms;
    this.typeLocality = typeLocality;
    this.typeDepository = typeDepository;
    this.fullDescriptionUnstructured = fullDescriptionUnstructured;
    this.molecularDataUnstructure = molecularDataUnstructure;
    this.crDistribution = crDistribution;
    this.regionalDistribution = regionalDistribution;
    this.annualCyclesUnstructure = annualCyclesUnstructure;
    this.collectingMethod = collectingMethod;
    this.usesUnstructure = usesUnstructure;
    this.myths = myths;
    this.lifeCycleUnstructure = lifeCycleUnstructure;
    this.interactionUnstructure = interactionUnstructure;
    this.lifeFormUnstructure = lifeFormUnstructure;
    this.reproductionUnstructure = reproductionUnstructure;
    this.populationBiologyUnstructure = populationBiologyUnstructure;
    this.demographyUnstructure = demographyUnstructure;
    this.threatUnstructure = threatUnstructure;
    this.references = references;
    this.urlfigure1 = urlfigure1;
    this.urldescriptionfigure = urldescriptionfigure;
    this.published = published;
    this.urldistributionmap = urldistributionmap;
    this.urlfigure2 = urlfigure2;
    this.urlfigure3 = urlfigure3;
    this.captiondescriptionfigure = captiondescriptionfigure;
    this.idversionanterior = idversionanterior;
    this.hasversion = hasversion;
    this.colaborator1 = colaborator1;
    this.colaborator2 = colaborator2;
    this.captionfigure1 = captionfigure1;
    this.captionfigure2 = captionfigure2;
    this.captionfigure3 = captionfigure3;
    this.family = family;
    this.genus = genus;
    this.order = order;
    this.publishedin = publishedin;
    this.typecollector = typecollector;
    this.habitatUnstructure = habitatUnstructure;
    this.territoryUnstructure = territoryUnstructure;
    this.feedingUnstructure = feedingUnstructure;
    this.captiondistributionmap = captiondistributionmap;
    this.phenologyUnstructure = phenologyUnstructure;
    this.conservationareadistribution = conservationareadistribution;
    this.visible = visible;
    this.coauthor1 = coauthor1;
    this.coauthor2 = coauthor2;
    this.emailauthor = emailauthor;
    this.behaviorUnstructure = behaviorUnstructure;
    this.urlthumbnail = urlthumbnail;
    this.creationdate = creationdate;
    this.modificationdate = modificationdate;
    this.createdby = createdby;
    this.lastmodificationby = lastmodificationby;
    this.threatStatus = threatStatus;
    this.recordurl = recordurl;
    this.urllogo1 = urllogo1;
    this.urllogo2 = urllogo2;
    this.speciesrecordstatus = speciesrecordstatus;
    this.philologist = philologist;
    this.subfamily = subfamily;
    this.language = language;
    this.esMetaDescriptors = esMetaDescriptors;
    this.enMetaDescriptors = enMetaDescriptors;
    this.species = species;
    this.citesThreatStatus = citesThreatStatus;
    this.uicnThreatStatus = uicnThreatStatus;
    this.wildProtectedAreaDistribution = wildProtectedAreaDistribution;
    this.etymology = etymology;
    this.urlvideo = urlvideo;
    this.taxon = taxon;
    this.books = books;

  }

  public BigDecimal getTaxonRecordId() {
    return this.taxonRecordId;
  }

  public void setTaxonRecordId(BigDecimal taxonRecordId) {
    this.taxonRecordId = taxonRecordId;
  }

  public BigDecimal getVersion() {
    return this.version;
  }

  public void setVersion(BigDecimal version) {
    this.version = version;
  }

  public String getScientificName() {
    return this.scientificName;
  }

  public void setScientificName(String scientificName) {
    this.scientificName = scientificName;
  }

  public String getScientificNameAuthorship() {
    return this.scientificNameAuthorship;
  }

  public void setScientificNameAuthorship(String scientificNameAuthorship) {
    this.scientificNameAuthorship = scientificNameAuthorship;
  }

  public String getNamePublishedInYear() {
    return this.namePublishedInYear;
  }

  public void setNamePublishedInYear(String namePublishedInYear) {
    this.namePublishedInYear = namePublishedInYear;
  }

  public String getIndividualName() {
    return this.individualName;
  }

  public void setIndividualName(String individualName) {
    this.individualName = individualName;
  }

  public String getDateIssued() {
    return this.dateIssued;
  }

  public void setDateIssued(String dateIssued) {
    this.dateIssued = dateIssued;
  }

  public String getCommonNamesUnstructured() {
    return this.commonNamesUnstructured;
  }

  public void setCommonNamesUnstructured(String commonNamesUnstructured) {
    this.commonNamesUnstructured = commonNamesUnstructured;
  }

  public String getSynonyms() {
    return this.synonyms;
  }

  public void setSynonyms(String synonyms) {
    this.synonyms = synonyms;
  }

  public String getTypeLocality() {
    return this.typeLocality;
  }

  public void setTypeLocality(String typeLocality) {
    this.typeLocality = typeLocality;
  }

  public String getTypeDepository() {
    return this.typeDepository;
  }

  public void setTypeDepository(String typeDepository) {
    this.typeDepository = typeDepository;
  }

  public String getFullDescriptionUnstructured() {
    return this.fullDescriptionUnstructured;
  }

  public void setFullDescriptionUnstructured(String fullDescriptionUnstructured) {
    this.fullDescriptionUnstructured = fullDescriptionUnstructured;
  }

  public String getMolecularDataUnstructure() {
    return this.molecularDataUnstructure;
  }

  public void setMolecularDataUnstructure(String molecularDataUnstructure) {
    this.molecularDataUnstructure = molecularDataUnstructure;
  }

  public String getCrDistribution() {
    return this.crDistribution;
  }

  public void setCrDistribution(String crDistribution) {
    this.crDistribution = crDistribution;
  }

  public String getRegionalDistribution() {
    return this.regionalDistribution;
  }

  public void setRegionalDistribution(String regionalDistribution) {
    this.regionalDistribution = regionalDistribution;
  }

  public String getAnnualCyclesUnstructure() {
    return this.annualCyclesUnstructure;
  }

  public void setAnnualCyclesUnstructure(String annualCyclesUnstructure) {
    this.annualCyclesUnstructure = annualCyclesUnstructure;
  }

  public String getCollectingMethod() {
    return this.collectingMethod;
  }

  public void setCollectingMethod(String collectingMethod) {
    this.collectingMethod = collectingMethod;
  }

  public String getUsesUnstructure() {
    return this.usesUnstructure;
  }

  public void setUsesUnstructure(String usesUnstructure) {
    this.usesUnstructure = usesUnstructure;
  }

  public String getMyths() {
    return this.myths;
  }

  public void setMyths(String myths) {
    this.myths = myths;
  }

  public String getLifeCycleUnstructure() {
    return this.lifeCycleUnstructure;
  }

  public void setLifeCycleUnstructure(String lifeCycleUnstructure) {
    this.lifeCycleUnstructure = lifeCycleUnstructure;
  }

  public String getInteractionUnstructure() {
    return this.interactionUnstructure;
  }

  public void setInteractionUnstructure(String interactionUnstructure) {
    this.interactionUnstructure = interactionUnstructure;
  }

  public String getLifeFormUnstructure() {
    return this.lifeFormUnstructure;
  }

  public void setLifeFormUnstructure(String lifeFormUnstructure) {
    this.lifeFormUnstructure = lifeFormUnstructure;
  }

  public String getReproductionUnstructure() {
    return this.reproductionUnstructure;
  }

  public void setReproductionUnstructure(String reproductionUnstructure) {
    this.reproductionUnstructure = reproductionUnstructure;
  }

  public String getPopulationBiologyUnstructure() {
    return this.populationBiologyUnstructure;
  }

  public void setPopulationBiologyUnstructure(String populationBiologyUnstructure) {
    this.populationBiologyUnstructure = populationBiologyUnstructure;
  }

  public String getDemographyUnstructure() {
    return this.demographyUnstructure;
  }

  public void setDemographyUnstructure(String demographyUnstructure) {
    this.demographyUnstructure = demographyUnstructure;
  }

  public String getThreatUnstructure() {
    return this.threatUnstructure;
  }

  public void setThreatUnstructure(String threatUnstructure) {
    this.threatUnstructure = threatUnstructure;
  }

  public String getReferences() {
    return this.references;
  }

  public void setReferences(String references) {
    this.references = references;
  }

  public String getUrlfigure1() {
    return this.urlfigure1;
  }

  public void setUrlfigure1(String urlfigure1) {
    this.urlfigure1 = urlfigure1;
  }

  public String getUrldescriptionfigure() {
    return this.urldescriptionfigure;
  }

  public void setUrldescriptionfigure(String urldescriptionfigure) {
    this.urldescriptionfigure = urldescriptionfigure;
  }

  public String getPublished() {
    return this.published;
  }

  public void setPublished(String published) {
    this.published = published;
  }

  public String getUrldistributionmap() {
    return this.urldistributionmap;
  }

  public void setUrldistributionmap(String urldistributionmap) {
    this.urldistributionmap = urldistributionmap;
  }

  public String getUrlfigure2() {
    return this.urlfigure2;
  }

  public void setUrlfigure2(String urlfigure2) {
    this.urlfigure2 = urlfigure2;
  }

  public String getUrlfigure3() {
    return this.urlfigure3;
  }

  public void setUrlfigure3(String urlfigure3) {
    this.urlfigure3 = urlfigure3;
  }

  public String getCaptiondescriptionfigure() {
    return this.captiondescriptionfigure;
  }

  public void setCaptiondescriptionfigure(String captiondescriptionfigure) {
    this.captiondescriptionfigure = captiondescriptionfigure;
  }

  public String getIdversionanterior() {
    return this.idversionanterior;
  }

  public void setIdversionanterior(String idversionanterior) {
    this.idversionanterior = idversionanterior;
  }

  public String getHasversion() {
    return this.hasversion;
  }

  public void setHasversion(String hasversion) {
    this.hasversion = hasversion;
  }

  public String getColaborator1() {
    return this.colaborator1;
  }

  public void setColaborator1(String colaborator1) {
    this.colaborator1 = colaborator1;
  }

  public String getColaborator2() {
    return this.colaborator2;
  }

  public void setColaborator2(String colaborator2) {
    this.colaborator2 = colaborator2;
  }

  public String getCaptionfigure1() {
    return this.captionfigure1;
  }

  public void setCaptionfigure1(String captionfigure1) {
    this.captionfigure1 = captionfigure1;
  }

  public String getCaptionfigure2() {
    return this.captionfigure2;
  }

  public void setCaptionfigure2(String captionfigure2) {
    this.captionfigure2 = captionfigure2;
  }

  public String getCaptionfigure3() {
    return this.captionfigure3;
  }

  public void setCaptionfigure3(String captionfigure3) {
    this.captionfigure3 = captionfigure3;
  }

  public String getFamily() {
    return this.family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public String getGenus() {
    return this.genus;
  }

  public void setGenus(String genus) {
    this.genus = genus;
  }

  public String getOrder() {
    return this.order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public String getPublishedin() {
    return this.publishedin;
  }

  public void setPublishedin(String publishedin) {
    this.publishedin = publishedin;
  }

  public String getTypecollector() {
    return this.typecollector;
  }

  public void setTypecollector(String typecollector) {
    this.typecollector = typecollector;
  }

  public String getHabitatUnstructure() {
    return this.habitatUnstructure;
  }

  public void setHabitatUnstructure(String habitatUnstructure) {
    this.habitatUnstructure = habitatUnstructure;
  }

  public String getTerritoryUnstructure() {
    return this.territoryUnstructure;
  }

  public void setTerritoryUnstructure(String territoryUnstructure) {
    this.territoryUnstructure = territoryUnstructure;
  }

  public String getFeedingUnstructure() {
    return this.feedingUnstructure;
  }

  public void setFeedingUnstructure(String feedingUnstructure) {
    this.feedingUnstructure = feedingUnstructure;
  }

  public String getCaptiondistributionmap() {
    return this.captiondistributionmap;
  }

  public void setCaptiondistributionmap(String captiondistributionmap) {
    this.captiondistributionmap = captiondistributionmap;
  }

  public String getPhenologyUnstructure() {
    return this.phenologyUnstructure;
  }

  public void setPhenologyUnstructure(String phenologyUnstructure) {
    this.phenologyUnstructure = phenologyUnstructure;
  }

  public String getConservationareadistribution() {
    return this.conservationareadistribution;
  }

  public void setConservationareadistribution(String conservationareadistribution) {
    this.conservationareadistribution = conservationareadistribution;
  }

  public String getVisible() {
    return this.visible;
  }

  public void setVisible(String visible) {
    this.visible = visible;
  }

  public String getCoauthor1() {
    return this.coauthor1;
  }

  public void setCoauthor1(String coauthor1) {
    this.coauthor1 = coauthor1;
  }

  public String getCoauthor2() {
    return this.coauthor2;
  }

  public void setCoauthor2(String coauthor2) {
    this.coauthor2 = coauthor2;
  }

  public String getEmailauthor() {
    return this.emailauthor;
  }

  public void setEmailauthor(String emailauthor) {
    this.emailauthor = emailauthor;
  }

  public String getBehaviorUnstructure() {
    return this.behaviorUnstructure;
  }

  public void setBehaviorUnstructure(String behaviorUnstructure) {
    this.behaviorUnstructure = behaviorUnstructure;
  }

  public String getUrlthumbnail() {
    return this.urlthumbnail;
  }

  public void setUrlthumbnail(String urlthumbnail) {
    this.urlthumbnail = urlthumbnail;
  }

  public String getCreationdate() {
    return this.creationdate;
  }

  public void setCreationdate(String creationdate) {
    this.creationdate = creationdate;
  }

  public String getModificationdate() {
    return this.modificationdate;
  }

  public void setModificationdate(String modificationdate) {
    this.modificationdate = modificationdate;
  }

  public String getCreatedby() {
    return this.createdby;
  }

  public void setCreatedby(String createdby) {
    this.createdby = createdby;
  }

  public String getLastmodificationby() {
    return this.lastmodificationby;
  }

  public void setLastmodificationby(String lastmodificationby) {
    this.lastmodificationby = lastmodificationby;
  }

  public String getThreatStatus() {
    return this.threatStatus;
  }

  public void setThreatStatus(String threatStatus) {
    this.threatStatus = threatStatus;
  }

  public String getRecordurl() {
    return this.recordurl;
  }

  public void setRecordurl(String recordurl) {
    this.recordurl = recordurl;
  }

  public String getUrllogo1() {
    return this.urllogo1;
  }

  public void setUrllogo1(String urllogo1) {
    this.urllogo1 = urllogo1;
  }

  public String getUrllogo2() {
    return this.urllogo2;
  }

  public void setUrllogo2(String urllogo2) {
    this.urllogo2 = urllogo2;
  }

  public String getSpeciesrecordstatus() {
    return this.speciesrecordstatus;
  }

  public void setSpeciesrecordstatus(String speciesrecordstatus) {
    this.speciesrecordstatus = speciesrecordstatus;
  }

  public String getPhilologist() {
    return this.philologist;
  }

  public void setPhilologist(String philologist) {
    this.philologist = philologist;
  }

  public String getSubfamily() {
    return this.subfamily;
  }

  public void setSubfamily(String subfamily) {
    this.subfamily = subfamily;
  }

  public String getLanguage() {
    return this.language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public String getEsMetaDescriptors() {
    return this.esMetaDescriptors;
  }

  public void setEsMetaDescriptors(String esMetaDescriptors) {
    this.esMetaDescriptors = esMetaDescriptors;
  }

  public String getEnMetaDescriptors() {
    return this.enMetaDescriptors;
  }

  public void setEnMetaDescriptors(String enMetaDescriptors) {
    this.enMetaDescriptors = enMetaDescriptors;
  }

  public String getSpecies() {
    return this.species;
  }

  public void setSpecies(String species) {
    this.species = species;
  }

  public String getCitesThreatStatus() {
    return this.citesThreatStatus;
  }

  public void setCitesThreatStatus(String citesThreatStatus) {
    this.citesThreatStatus = citesThreatStatus;
  }

  public String getUicnThreatStatus() {
    return this.uicnThreatStatus;
  }

  public void setUicnThreatStatus(String uicnThreatStatus) {
    this.uicnThreatStatus = uicnThreatStatus;
  }

  public String getWildProtectedAreaDistribution() {
    return this.wildProtectedAreaDistribution;
  }

  public void setWildProtectedAreaDistribution(String wildProtectedAreaDistribution) {
    this.wildProtectedAreaDistribution = wildProtectedAreaDistribution;
  }

  public String getEtymology() {
    return this.etymology;
  }

  public void setEtymology(String etymology) {
    this.etymology = etymology;
  }

  public String getUrlvideo() {
    return this.urlvideo;
  }

  public void setUrlvideo(String urlvideo) {
    this.urlvideo = urlvideo;
  }

  @JsonIgnore
  public Taxon getTaxon() {
    return this.taxon;
  }

  public void setTaxon(Taxon taxon) {
    this.taxon = taxon;
  }

  
  public Set<Book> getBooks() {
      return this.books;
  }


  public void setBooks(Set<Book> books) {
      this.books = books;
  }



  public static class CompDate implements Comparator<TaxonPlic>
  {
	  private int mod = 1;
	  public CompDate(boolean desc)
	  {
		  if(desc) mod =-1;
	  }
	@Override
	public int compare(TaxonPlic o1, TaxonPlic o2) 
	{
		return mod*o1.dateIssued.compareTo(o2.dateIssued);
	}
	  
  }

}


