package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * TaxonHasAssociatedAttributeId generated by hbm2java
 */

public class TaxonHasAssociatedAttributeId  implements java.io.Serializable {


    // Fields    

     private BigDecimal taxonId;
     private BigDecimal associatedAttributeId;


    // Constructors

    /** default constructor */
    public TaxonHasAssociatedAttributeId() {
    }

    
    /** full constructor */
    public TaxonHasAssociatedAttributeId(BigDecimal taxonId, BigDecimal associatedAttributeId) {
        this.taxonId = taxonId;
        this.associatedAttributeId = associatedAttributeId;
    }
    

   
    // Property accessors

    public BigDecimal getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(BigDecimal taxonId) {
        this.taxonId = taxonId;
    }

    public BigDecimal getAssociatedAttributeId() {
        return this.associatedAttributeId;
    }
    
    public void setAssociatedAttributeId(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxonHasAssociatedAttributeId) ) return false;
		 TaxonHasAssociatedAttributeId castOther = ( TaxonHasAssociatedAttributeId ) other; 
         
		 return ( (this.getTaxonId()==castOther.getTaxonId()) || ( this.getTaxonId()!=null && castOther.getTaxonId()!=null && this.getTaxonId().equals(castOther.getTaxonId()) ) )
 && ( (this.getAssociatedAttributeId()==castOther.getAssociatedAttributeId()) || ( this.getAssociatedAttributeId()!=null && castOther.getAssociatedAttributeId()!=null && this.getAssociatedAttributeId().equals(castOther.getAssociatedAttributeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxonId() == null ? 0 : this.getTaxonId().hashCode() );
         result = 37 * result + ( getAssociatedAttributeId() == null ? 0 : this.getAssociatedAttributeId().hashCode() );
         return result;
   }   





}
