package org.inbio.neoportal.core.entity;
// Generated 02/03/2011 05:06:45 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * TaxonHasReferenceElementId generated by hbm2java
 */

public class TaxonHasReferenceElementId  implements java.io.Serializable {


    // Fields    

     private BigDecimal taxonId;
     private BigDecimal referenceElementId;


    // Constructors

    /** default constructor */
    public TaxonHasReferenceElementId() {
    }

    
    /** full constructor */
    public TaxonHasReferenceElementId(BigDecimal taxonId, BigDecimal referenceElementId) {
        this.taxonId = taxonId;
        this.referenceElementId = referenceElementId;
    }
    

   
    // Property accessors

    public BigDecimal getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(BigDecimal taxonId) {
        this.taxonId = taxonId;
    }

    public BigDecimal getReferenceElementId() {
        return this.referenceElementId;
    }
    
    public void setReferenceElementId(BigDecimal referenceElementId) {
        this.referenceElementId = referenceElementId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxonHasReferenceElementId) ) return false;
		 TaxonHasReferenceElementId castOther = ( TaxonHasReferenceElementId ) other; 
         
		 return ( (this.getTaxonId()==castOther.getTaxonId()) || ( this.getTaxonId()!=null && castOther.getTaxonId()!=null && this.getTaxonId().equals(castOther.getTaxonId()) ) )
 && ( (this.getReferenceElementId()==castOther.getReferenceElementId()) || ( this.getReferenceElementId()!=null && castOther.getReferenceElementId()!=null && this.getReferenceElementId().equals(castOther.getReferenceElementId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxonId() == null ? 0 : this.getTaxonId().hashCode() );
         result = 37 * result + ( getReferenceElementId() == null ? 0 : this.getReferenceElementId().hashCode() );
         return result;
   }   





}
