package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA



/**
 * TaxonAssociatedAttributeHasReferenceElement generated by hbm2java
 */
public class TaxonAssociatedAttributeHasReferenceElement  implements java.io.Serializable {


     private TaxonAssociatedAttributeHasReferenceElementId id;
     private TaxonHasAssociatedAttribute taxonHasAssociatedAttribute;
     private String value;

    public TaxonAssociatedAttributeHasReferenceElement() {
    }

	
    public TaxonAssociatedAttributeHasReferenceElement(TaxonAssociatedAttributeHasReferenceElementId id, TaxonHasAssociatedAttribute taxonHasAssociatedAttribute) {
        this.id = id;
        this.taxonHasAssociatedAttribute = taxonHasAssociatedAttribute;
    }
    public TaxonAssociatedAttributeHasReferenceElement(TaxonAssociatedAttributeHasReferenceElementId id, TaxonHasAssociatedAttribute taxonHasAssociatedAttribute, String value) {
       this.id = id;
       this.taxonHasAssociatedAttribute = taxonHasAssociatedAttribute;
       this.value = value;
    }
   
    public TaxonAssociatedAttributeHasReferenceElementId getId() {
        return this.id;
    }
    
    public void setId(TaxonAssociatedAttributeHasReferenceElementId id) {
        this.id = id;
    }
    public TaxonHasAssociatedAttribute getTaxonHasAssociatedAttribute() {
        return this.taxonHasAssociatedAttribute;
    }
    
    public void setTaxonHasAssociatedAttribute(TaxonHasAssociatedAttribute taxonHasAssociatedAttribute) {
        this.taxonHasAssociatedAttribute = taxonHasAssociatedAttribute;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


