package org.inbio.neoportal.core.entity;
// Generated 26/04/2012 10:06:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TaxonHasAssociatedAttributeId generated by hbm2java
 */
public class TaxonHasAssociatedAttributeId  implements java.io.Serializable {


     private BigDecimal taxonId;
     private BigDecimal associatedAttributeId;

    public TaxonHasAssociatedAttributeId() {
    }

    public TaxonHasAssociatedAttributeId(BigDecimal taxonId, BigDecimal associatedAttributeId) {
       this.taxonId = taxonId;
       this.associatedAttributeId = associatedAttributeId;
    }
   
    public BigDecimal getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(BigDecimal taxonId) {
        this.taxonId = taxonId;
    }
    public BigDecimal getAssociatedAttributeId() {
        return this.associatedAttributeId;
    }
    
    public void setAssociatedAttributeId(BigDecimal associatedAttributeId) {
        this.associatedAttributeId = associatedAttributeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxonHasAssociatedAttributeId) ) return false;
		 TaxonHasAssociatedAttributeId castOther = ( TaxonHasAssociatedAttributeId ) other; 
         
		 return ( (this.getTaxonId()==castOther.getTaxonId()) || ( this.getTaxonId()!=null && castOther.getTaxonId()!=null && this.getTaxonId().equals(castOther.getTaxonId()) ) )
 && ( (this.getAssociatedAttributeId()==castOther.getAssociatedAttributeId()) || ( this.getAssociatedAttributeId()!=null && castOther.getAssociatedAttributeId()!=null && this.getAssociatedAttributeId().equals(castOther.getAssociatedAttributeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxonId() == null ? 0 : this.getTaxonId().hashCode() );
         result = 37 * result + ( getAssociatedAttributeId() == null ? 0 : this.getAssociatedAttributeId().hashCode() );
         return result;
   }   


}


